// GENERATED by scripts/sdk/generate-sdks.mts from the CommandAGI SDK schema — do not edit by hand.
/* eslint-disable */

export type Args = Record<string, unknown>;

/** The one environment every SDK reads — and the one the platform injects where it runs your code. */
export const ENV = {
  apiKey: "COMMANDAGI_API_KEY",
  baseUrl: "COMMANDAGI_BASE_URL",
  threadId: "COMMANDAGI_THREAD_ID",
} as const;
export const DEFAULT_BASE_URL = "https://api.commandagi.com";

/** The composed, language-neutral schema every SDK is generated from. */
export const SDK_SCHEMA = {
  $comment:
    "GENERATED by scripts/sdk/generate-sdks.mts from the CommandAGI SDK schema — do not edit by hand.",
  version: 1,
  env: {
    apiKey: "COMMANDAGI_API_KEY",
    baseUrl: "COMMANDAGI_BASE_URL",
    threadId: "COMMANDAGI_THREAD_ID",
  },
  defaultBaseUrl: "https://api.commandagi.com",
  tools: {
    transport:
      "POST {baseUrl}/mcp — JSON-RPC 2.0 `tools/call` {name, arguments}, `authorization: Bearer {apiKey}`; the result's text content is JSON. `call(tool, args)` reaches ANY platform tool by name.",
    root: [
      {
        name: "whoami",
        tool: "whoami",
        doc: "The account this key belongs to.",
        params: [],
        bound: {},
        withThread: false,
      },
      {
        name: "search",
        tool: "search_tools",
        doc: "Search the whole tool catalog by keyword.",
        params: [
          {
            name: "query",
            key: "query",
            type: "string",
            required: true,
            spread: false,
            prefix: null,
            cli: "join",
          },
          {
            name: "limit",
            key: "limit",
            type: "integer",
            required: false,
            spread: false,
            prefix: null,
            cli: "flag",
          },
        ],
        bound: {},
        withThread: false,
      },
      {
        name: "run",
        tool: "run_code",
        doc: "Run a snippet server-side (JavaScript / TypeScript / Python).",
        params: [
          {
            name: "code",
            key: "code",
            type: "string",
            required: true,
            spread: false,
            prefix: null,
            cli: "file",
          },
          {
            name: "language",
            key: "language",
            type: "string",
            required: false,
            spread: false,
            prefix: null,
            cli: "language",
          },
          {
            name: "threadId",
            key: "threadId",
            type: "string",
            required: false,
            spread: false,
            prefix: null,
            cli: "flag",
          },
        ],
        bound: {},
        withThread: true,
      },
      {
        name: "post",
        tool: "post",
        doc: "Publish a file to a connected social account.",
        params: [
          {
            name: "opts",
            key: null,
            type: "object",
            required: false,
            spread: true,
            prefix: null,
            cli: "spread",
          },
        ],
        bound: {},
        withThread: false,
      },
    ],
    namespaces: [
      {
        name: "threads",
        doc: "Agent threads — the unit of work.",
        factory: null,
        methods: [
          {
            name: "list",
            tool: "list_threads",
            doc: "Your threads.",
            params: [],
            bound: {},
            withThread: false,
          },
          {
            name: "get",
            tool: "get_thread",
            doc: "One thread's detail.",
            params: [
              {
                name: "threadId",
                key: "threadId",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "create",
            tool: "create_thread",
            doc: "Spawn a thread: {intent, snapshotId?, …}, or {agentless: true, snapshotId} for a world you drive.",
            params: [
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "send",
            tool: "send_message",
            doc: "Message a thread.",
            params: [
              {
                name: "threadId",
                key: "threadId",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "text",
                key: "text",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "join",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "events",
            tool: "thread_events",
            doc: "A thread's event log.",
            params: [
              {
                name: "threadId",
                key: "threadId",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "kill",
            tool: "kill_process",
            doc: "Stop a thread's run (the thread itself persists).",
            params: [
              {
                name: "threadId",
                key: "pid",
                type: "string",
                required: true,
                spread: false,
                prefix: "thread:",
                cli: "positional",
              },
            ],
            bound: {},
            withThread: false,
          },
        ],
      },
      {
        name: "embodiments",
        doc: "Computers, cameras, robots and sims attached to a thread.",
        factory: null,
        methods: [
          {
            name: "list",
            tool: "list_embodiments",
            doc: "Attached embodiments.",
            params: [],
            bound: {},
            withThread: false,
          },
          {
            name: "launch",
            tool: "launch_embodiment",
            doc: "Launch an embodiment into the thread: {kind?, snapshotId?, fromSnapshotId?}.",
            params: [
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: true,
          },
          {
            name: "observe",
            tool: "observe",
            doc: "The thread's observation plane: stream channels and the latest frame per embodiment.",
            params: [
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: true,
          },
          {
            name: "controls",
            tool: "list_controls",
            doc: "What an embodiment can be driven with right now: channels, actions, payload schemas.",
            params: [
              {
                name: "embodimentId",
                key: "embodimentId",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "threadId",
                key: "threadId",
                type: "string",
                required: false,
                spread: false,
                prefix: null,
                cli: "flag",
              },
            ],
            bound: {},
            withThread: true,
          },
          {
            name: "act",
            tool: "act",
            doc: "Drive an embodiment with one declared action (see controls).",
            params: [
              {
                name: "embodimentId",
                key: "embodimentId",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "action",
                key: "action",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "payload",
                key: "payload",
                type: "object",
                required: false,
                spread: false,
                prefix: null,
                cli: "json",
              },
              {
                name: "threadId",
                key: "threadId",
                type: "string",
                required: false,
                spread: false,
                prefix: null,
                cli: "flag",
              },
            ],
            bound: {},
            withThread: true,
          },
          {
            name: "describe",
            tool: "describe_world",
            doc: "The live sim/robot world: robots, objects and poses the runtime reports.",
            params: [
              {
                name: "threadId",
                key: "threadId",
                type: "string",
                required: false,
                spread: false,
                prefix: null,
                cli: "flag",
              },
            ],
            bound: {},
            withThread: true,
          },
        ],
      },
      {
        name: "memory",
        doc: "The agent's durable memory: markdown files under memories/ in the thread's drive.",
        factory: null,
        methods: [
          {
            name: "search",
            tool: "memory_search",
            doc: "Recall by query (the drive's content index over memories/).",
            params: [
              {
                name: "query",
                key: "q",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "join",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "remember",
            tool: "memory_remember",
            doc: "Write a memory file.",
            params: [
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "forget",
            tool: "memory_forget",
            doc: "Delete a memory file by its path.",
            params: [
              {
                name: "path",
                key: "path",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
            ],
            bound: {},
            withThread: false,
          },
        ],
      },
      {
        name: "integrations",
        doc: "Connected third-party accounts.",
        factory: null,
        methods: [
          {
            name: "list",
            tool: "list_integrations",
            doc: "What's connected.",
            params: [],
            bound: {},
            withThread: false,
          },
          {
            name: "call",
            tool: "integration_call",
            doc: "Drive a provider's API (method/path/query/body).",
            params: [
              {
                name: "integration",
                key: "integration",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: false,
          },
        ],
      },
      {
        name: "social",
        doc: "A single connected social account, bound: cagi.social('tiktok', '@brand').post(fileId).",
        factory: [
          {
            name: "platform",
            key: "platform",
            type: "string",
            required: true,
            spread: false,
            prefix: null,
            cli: "positional",
          },
          {
            name: "account",
            key: "account",
            type: "string",
            required: false,
            spread: false,
            prefix: null,
            cli: "flag",
          },
        ],
        methods: [
          {
            name: "post",
            tool: "post",
            doc: "Publish a stored file to this account.",
            params: [
              {
                name: "fileId",
                key: "fileId",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: { integration: "platform", account: "account" },
            withThread: false,
          },
          {
            name: "call",
            tool: "integration_call",
            doc: "Raw API call as this account.",
            params: [
              {
                name: "method",
                key: "method",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "path",
                key: "path",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: { integration: "platform", account: "account" },
            withThread: false,
          },
        ],
      },
    ],
  },
  session: {
    transport:
      "Frames: WebSocket {baseUrl→ws}/rt/thread/{threadId}?token={apiKey}; server messages `frame` {embodimentId, channelId, url} carry the latest image (a data: URL or an https URL fetched with the same bearer). Control: every vocabulary method is `embodiments.act(embodimentId, action, payload)` — the thread resolves the action against what that embodiment live-declares (embodiments.controls).",
    vocabularies: [
      {
        name: "desktop",
        doc: "Computers — pointer, keyboard and waits.",
        actions: [
          {
            name: "click",
            channelId: "pointer",
            label: "Pointer",
            schema: {
              type: "object",
              properties: {
                x: { type: "number", minimum: -100000, maximum: 100000 },
                y: { type: "number", minimum: -100000, maximum: 100000 },
              },
              required: ["x", "y"],
              additionalProperties: false,
            },
          },
          {
            name: "double_click",
            channelId: "pointer",
            label: "Pointer",
            schema: {
              type: "object",
              properties: {
                x: { type: "number", minimum: -100000, maximum: 100000 },
                y: { type: "number", minimum: -100000, maximum: 100000 },
              },
              required: ["x", "y"],
              additionalProperties: false,
            },
          },
          {
            name: "right_click",
            channelId: "pointer",
            label: "Pointer",
            schema: {
              type: "object",
              properties: {
                x: { type: "number", minimum: -100000, maximum: 100000 },
                y: { type: "number", minimum: -100000, maximum: 100000 },
              },
              required: ["x", "y"],
              additionalProperties: false,
            },
          },
          {
            name: "middle_click",
            channelId: "pointer",
            label: "Pointer",
            schema: {
              type: "object",
              properties: {
                x: { type: "number", minimum: -100000, maximum: 100000 },
                y: { type: "number", minimum: -100000, maximum: 100000 },
              },
              required: ["x", "y"],
              additionalProperties: false,
            },
          },
          {
            name: "move",
            channelId: "pointer",
            label: "Pointer",
            schema: {
              type: "object",
              properties: {
                x: { type: "number", minimum: -100000, maximum: 100000 },
                y: { type: "number", minimum: -100000, maximum: 100000 },
              },
              required: ["x", "y"],
              additionalProperties: false,
            },
          },
          {
            name: "scroll",
            channelId: "pointer",
            label: "Pointer",
            schema: {
              type: "object",
              properties: {
                x: { type: "number", minimum: -100000, maximum: 100000 },
                y: { type: "number", minimum: -100000, maximum: 100000 },
                dx: { type: "number", minimum: -100000, maximum: 100000 },
                dy: { type: "number", minimum: -100000, maximum: 100000 },
              },
              required: ["dy"],
              additionalProperties: false,
            },
          },
          {
            name: "type",
            channelId: "keyboard",
            label: "Keyboard",
            schema: {
              type: "object",
              properties: { text: { type: "string", maxLength: 131072 } },
              required: ["text"],
              additionalProperties: false,
            },
          },
          {
            name: "key",
            channelId: "keyboard",
            label: "Keyboard",
            schema: {
              type: "object",
              properties: { key: { type: "string", minLength: 1, maxLength: 256 } },
              required: ["key"],
              additionalProperties: false,
            },
          },
          {
            name: "wait",
            channelId: "ctrl",
            label: "Control",
            schema: {
              type: "object",
              properties: { ms: { type: "number", minimum: 0, maximum: 600000 } },
              additionalProperties: false,
            },
          },
        ],
      },
      {
        name: "robot",
        doc: "Physical robots driven through a robot driver (joints, gripper, drive).",
        actions: [
          {
            name: "joint",
            channelId: "ctrl",
            label: "Robot driver",
            schema: {
              type: "object",
              properties: {
                name: { type: "string", minLength: 1, maxLength: 256 },
                value: { type: "number", minimum: -1, maximum: 1 },
              },
              required: ["name", "value"],
              additionalProperties: false,
            },
          },
          {
            name: "pose",
            channelId: "ctrl",
            label: "Robot driver",
            schema: {
              type: "object",
              properties: { pose: { type: "object", additionalProperties: true } },
              required: ["pose"],
              additionalProperties: false,
            },
          },
          {
            name: "gripper",
            channelId: "ctrl",
            label: "Robot driver",
            schema: {
              type: "object",
              properties: { value: { type: "number", minimum: -1, maximum: 1 } },
              required: ["value"],
              additionalProperties: false,
            },
          },
          {
            name: "home",
            channelId: "ctrl",
            label: "Robot driver",
            schema: { type: "object", additionalProperties: false },
          },
          {
            name: "reset",
            channelId: "ctrl",
            label: "Robot driver",
            schema: { type: "object", additionalProperties: false },
          },
          {
            name: "stop",
            channelId: "ctrl",
            label: "Robot driver",
            schema: { type: "object", additionalProperties: false },
          },
          {
            name: "move",
            channelId: "ctrl",
            label: "Robot driver",
            schema: {
              type: "object",
              properties: { value: { type: "number", minimum: -1, maximum: 1 } },
              additionalProperties: false,
            },
          },
          {
            name: "back",
            channelId: "ctrl",
            label: "Robot driver",
            schema: {
              type: "object",
              properties: { value: { type: "number", minimum: -1, maximum: 1 } },
              additionalProperties: false,
            },
          },
          {
            name: "turn",
            channelId: "ctrl",
            label: "Robot driver",
            schema: {
              type: "object",
              properties: { value: { type: "number", minimum: -1, maximum: 1 } },
              additionalProperties: false,
            },
          },
        ],
      },
      {
        name: "sim",
        doc: "Simulated worlds — lifecycle, interaction, and the robots inside them.",
        actions: [
          {
            name: "run",
            channelId: "ctrl",
            label: "Simulation lifecycle",
            schema: { type: "object", additionalProperties: false },
          },
          {
            name: "pause",
            channelId: "ctrl",
            label: "Simulation lifecycle",
            schema: { type: "object", additionalProperties: false },
          },
          {
            name: "step",
            channelId: "ctrl",
            label: "Simulation lifecycle",
            schema: {
              type: "object",
              properties: { n: { type: "integer", minimum: 1, maximum: 100000 } },
              additionalProperties: false,
            },
          },
          {
            name: "speed",
            channelId: "ctrl",
            label: "Simulation lifecycle",
            schema: {
              type: "object",
              properties: { x: { type: "number", minimum: 0, maximum: 64 } },
              required: ["x"],
              additionalProperties: false,
            },
          },
          {
            name: "reset",
            channelId: "ctrl",
            label: "Simulation lifecycle",
            schema: { type: "object", additionalProperties: false },
          },
          {
            name: "params",
            channelId: "ctrl",
            label: "Simulation lifecycle",
            schema: {
              type: "object",
              properties: { values: { type: "object", additionalProperties: true } },
              required: ["values"],
              additionalProperties: false,
            },
          },
          {
            name: "load",
            channelId: "ctrl",
            label: "Simulation lifecycle",
            schema: {
              type: "object",
              properties: {
                world: {
                  type: "object",
                  properties: {
                    name: { type: "string", minLength: 1, maxLength: 1024 },
                    kind: { type: "string", enum: ["simulation"] },
                    scene: { type: "object", additionalProperties: true },
                  },
                  required: ["name", "kind", "scene"],
                  additionalProperties: true,
                },
              },
              required: ["world"],
              additionalProperties: false,
            },
          },
          {
            name: "describe",
            channelId: "ctrl",
            label: "Simulation lifecycle",
            schema: { type: "object", additionalProperties: false },
          },
          {
            name: "grab",
            channelId: "ctrl",
            label: "Simulation force drag",
            schema: {
              type: "object",
              properties: {
                body: { type: "string", minLength: 1, maxLength: 1024 },
                local: {
                  type: "array",
                  minItems: 3,
                  maxItems: 3,
                  items: { type: "number", minimum: -1000000000, maximum: 1000000000 },
                },
                target: {
                  type: "array",
                  minItems: 3,
                  maxItems: 3,
                  items: { type: "number", minimum: -1000000000, maximum: 1000000000 },
                },
                stiffness: { type: "number", minimum: 0, maximum: 1000000000 },
                damping: { type: "number", minimum: 0, maximum: 1000000000 },
                max_force: { type: "number", minimum: 0, maximum: 1000000000 },
                max_speed: { type: "number", minimum: 0, maximum: 1000000 },
              },
              required: ["body", "local", "target"],
              additionalProperties: false,
            },
          },
          {
            name: "drag",
            channelId: "ctrl",
            label: "Simulation force drag",
            schema: {
              type: "object",
              properties: {
                target: {
                  type: "array",
                  minItems: 3,
                  maxItems: 3,
                  items: { type: "number", minimum: -1000000000, maximum: 1000000000 },
                },
              },
              required: ["target"],
              additionalProperties: false,
            },
          },
          {
            name: "release",
            channelId: "ctrl",
            label: "Simulation force drag",
            schema: { type: "object", additionalProperties: false },
          },
          {
            name: "ctrl",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: {
                robotId: { type: "string", minLength: 1, maxLength: 1024 },
                targets: { type: "object", additionalProperties: true },
              },
              required: ["targets"],
              additionalProperties: false,
            },
          },
          {
            name: "actuator",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: {
                robotId: { type: "string", minLength: 1, maxLength: 1024 },
                name: { type: "string", minLength: 1, maxLength: 1024 },
                value: { type: "number", minimum: -1000000000, maximum: 1000000000 },
              },
              required: ["name", "value"],
              additionalProperties: false,
            },
          },
          {
            name: "pose",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: {
                robotId: { type: "string", minLength: 1, maxLength: 1024 },
                joints: { type: "object", additionalProperties: true },
              },
              required: ["joints"],
              additionalProperties: false,
            },
          },
          {
            name: "ik",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: {
                robotId: { type: "string", minLength: 1, maxLength: 1024 },
                target: {
                  type: "array",
                  minItems: 3,
                  maxItems: 3,
                  items: { type: "number", minimum: -1000000000, maximum: 1000000000 },
                },
                axis: {
                  type: "array",
                  minItems: 3,
                  maxItems: 3,
                  items: { type: "number", minimum: -1000000000, maximum: 1000000000 },
                },
                along: {
                  type: "array",
                  minItems: 3,
                  maxItems: 3,
                  items: { type: "number", minimum: -1000000000, maximum: 1000000000 },
                },
                tolerance: { type: "number", minimum: 0, maximum: 1 },
              },
              required: ["target"],
              additionalProperties: false,
            },
          },
          {
            name: "trajectory",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: {
                robotId: { type: "string", minLength: 1, maxLength: 1024 },
                waypoints: {
                  type: "array",
                  minItems: 1,
                  maxItems: 10000,
                  items: {
                    type: "object",
                    properties: {
                      at: { type: "number", minimum: 0, maximum: 1000000 },
                      targets: { type: "object", additionalProperties: true },
                    },
                    required: ["at", "targets"],
                    additionalProperties: false,
                  },
                },
              },
              required: ["waypoints"],
              additionalProperties: false,
            },
          },
          {
            name: "grip",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: {
                robotId: { type: "string", minLength: 1, maxLength: 1024 },
                close: { type: "boolean" },
              },
              required: ["close"],
              additionalProperties: false,
            },
          },
          {
            name: "stop",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: { robotId: { type: "string", minLength: 1, maxLength: 1024 } },
              additionalProperties: false,
            },
          },
          {
            name: "add_robot",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: {
                id: { type: "string", minLength: 1, maxLength: 48 },
                device: { type: "string", minLength: 1, maxLength: 1024 },
                definition: { type: "object", additionalProperties: true },
                at: {
                  type: "array",
                  minItems: 3,
                  maxItems: 3,
                  items: { type: "number", minimum: -1000000000, maximum: 1000000000 },
                },
                yaw: { type: "number", minimum: -1000000000, maximum: 1000000000 },
                joints: { type: "object", additionalProperties: true },
              },
              required: ["id", "device", "at"],
              additionalProperties: false,
            },
          },
          {
            name: "remove_robot",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: { robotId: { type: "string", minLength: 1, maxLength: 1024 } },
              additionalProperties: false,
            },
          },
        ],
      },
    ],
  },
} as const;

export interface Transport {
  call<T = unknown>(tool: string, args?: Args): Promise<T>;
  withThread(args: Args): Args;
}

/** Anything that can send one control action to one embodiment (a live Session). */
export interface Actor {
  act(action: string, payload: Args): Promise<unknown>;
}

/** Drop absent values: a tool distinguishes an omitted key from an explicit null. */
function prune(a: Args): Args {
  const out: Args = {};
  for (const [k, v] of Object.entries(a)) if (v !== undefined && v !== null) out[k] = v;
  return out;
}

/** Agent threads — the unit of work. */
export class Threads {
  constructor(private readonly t: Transport) {}
  /** Your threads. */
  list(): Promise<unknown> {
    return this.t.call("list_threads", {});
  }
  /** One thread's detail. */
  get(threadId: string): Promise<unknown> {
    return this.t.call("get_thread", prune({ threadId: threadId }));
  }
  /** Spawn a thread: {intent, snapshotId?, …}, or {agentless: true, snapshotId} for a world you drive. */
  create(opts: Args = {}): Promise<unknown> {
    return this.t.call("create_thread", { ...opts });
  }
  /** Message a thread. */
  send(threadId: string, text: string): Promise<unknown> {
    return this.t.call("send_message", prune({ threadId: threadId, text: text }));
  }
  /** A thread's event log. */
  events(threadId: string): Promise<unknown> {
    return this.t.call("thread_events", prune({ threadId: threadId }));
  }
  /** Stop a thread's run (the thread itself persists). */
  kill(threadId: string): Promise<unknown> {
    return this.t.call(
      "kill_process",
      prune({ pid: threadId == null ? undefined : "thread:" + threadId }),
    );
  }
}

/** Computers, cameras, robots and sims attached to a thread. */
export class Embodiments {
  constructor(private readonly t: Transport) {}
  /** Attached embodiments. */
  list(): Promise<unknown> {
    return this.t.call("list_embodiments", {});
  }
  /** Launch an embodiment into the thread: {kind?, snapshotId?, fromSnapshotId?}. */
  launch(opts: Args = {}): Promise<unknown> {
    return this.t.call("launch_embodiment", this.t.withThread({ ...opts }));
  }
  /** The thread's observation plane: stream channels and the latest frame per embodiment. */
  observe(opts: Args = {}): Promise<unknown> {
    return this.t.call("observe", this.t.withThread({ ...opts }));
  }
  /** What an embodiment can be driven with right now: channels, actions, payload schemas. */
  controls(embodimentId: string, threadId?: string): Promise<unknown> {
    return this.t.call(
      "list_controls",
      this.t.withThread(prune({ embodimentId: embodimentId, threadId: threadId })),
    );
  }
  /** Drive an embodiment with one declared action (see controls). */
  act(embodimentId: string, action: string, payload?: Args, threadId?: string): Promise<unknown> {
    return this.t.call(
      "act",
      this.t.withThread(
        prune({ embodimentId: embodimentId, action: action, payload: payload, threadId: threadId }),
      ),
    );
  }
  /** The live sim/robot world: robots, objects and poses the runtime reports. */
  describe(threadId?: string): Promise<unknown> {
    return this.t.call("describe_world", this.t.withThread(prune({ threadId: threadId })));
  }
}

/** The agent's durable memory: markdown files under memories/ in the thread's drive. */
export class Memory {
  constructor(private readonly t: Transport) {}
  /** Recall by query (the drive's content index over memories/). */
  search(query: string): Promise<unknown> {
    return this.t.call("memory_search", prune({ q: query }));
  }
  /** Write a memory file. */
  remember(opts: Args = {}): Promise<unknown> {
    return this.t.call("memory_remember", { ...opts });
  }
  /** Delete a memory file by its path. */
  forget(path: string): Promise<unknown> {
    return this.t.call("memory_forget", prune({ path: path }));
  }
}

/** Connected third-party accounts. */
export class Integrations {
  constructor(private readonly t: Transport) {}
  /** What's connected. */
  list(): Promise<unknown> {
    return this.t.call("list_integrations", {});
  }
  /** Drive a provider's API (method/path/query/body). */
  call(integration: string, opts: Args = {}): Promise<unknown> {
    return this.t.call("integration_call", { ...prune({ integration: integration }), ...opts });
  }
}

/** A single connected social account, bound: cagi.social('tiktok', '@brand').post(fileId). */
export class Social {
  constructor(
    private readonly t: Transport,
    readonly platform: string,
    readonly account?: string,
  ) {}
  /** Publish a stored file to this account. */
  post(fileId: string, opts: Args = {}): Promise<unknown> {
    return this.t.call("post", {
      ...prune({ integration: this.platform, account: this.account, fileId: fileId }),
      ...opts,
    });
  }
  /** Raw API call as this account. */
  call(method: string, path: string, opts: Args = {}): Promise<unknown> {
    return this.t.call("integration_call", {
      ...prune({ integration: this.platform, account: this.account, method: method, path: path }),
      ...opts,
    });
  }
}

/**
 * Everything above the transport. The hand-written client (./client.ts) implements `call` over
 * /mcp and `withThread`; every method here is sugar over those two.
 */
export abstract class GeneratedClient implements Transport {
  abstract call<T = unknown>(tool: string, args?: Args): Promise<T>;
  abstract withThread(args: Args): Args;
  /** Agent threads — the unit of work. */
  readonly threads = new Threads(this);
  /** Computers, cameras, robots and sims attached to a thread. */
  readonly embodiments = new Embodiments(this);
  /** The agent's durable memory: markdown files under memories/ in the thread's drive. */
  readonly memory = new Memory(this);
  /** Connected third-party accounts. */
  readonly integrations = new Integrations(this);
  /** A single connected social account, bound: cagi.social('tiktok', '@brand').post(fileId). */
  social(platform: string, account?: string): Social {
    return new Social(this, platform, account);
  }
  /** The account this key belongs to. */
  whoami(): Promise<unknown> {
    return this.call("whoami", {});
  }
  /** Search the whole tool catalog by keyword. */
  search(query: string, limit?: number): Promise<unknown> {
    return this.call("search_tools", prune({ query: query, limit: limit }));
  }
  /** Run a snippet server-side (JavaScript / TypeScript / Python). */
  run(code: string, language?: string, threadId?: string): Promise<unknown> {
    return this.call(
      "run_code",
      this.withThread(prune({ code: code, language: language, threadId: threadId })),
    );
  }
  /** Publish a file to a connected social account. */
  post(opts: Args = {}): Promise<unknown> {
    return this.call("post", { ...opts });
  }
}

/** Computers — pointer, keyboard and waits. Each method is `act(action, payload)` on the embodiment this is bound to. */
export class DesktopControls {
  constructor(private readonly a: Actor) {}
  /** Pointer · `click` */
  click(payload: { x: number; y: number }): Promise<unknown> {
    return this.a.act("click", payload);
  }
  /** Pointer · `double_click` */
  doubleClick(payload: { x: number; y: number }): Promise<unknown> {
    return this.a.act("double_click", payload);
  }
  /** Pointer · `right_click` */
  rightClick(payload: { x: number; y: number }): Promise<unknown> {
    return this.a.act("right_click", payload);
  }
  /** Pointer · `middle_click` */
  middleClick(payload: { x: number; y: number }): Promise<unknown> {
    return this.a.act("middle_click", payload);
  }
  /** Pointer · `move` */
  move(payload: { x: number; y: number }): Promise<unknown> {
    return this.a.act("move", payload);
  }
  /** Pointer · `scroll` */
  scroll(payload: { x?: number; y?: number; dx?: number; dy: number }): Promise<unknown> {
    return this.a.act("scroll", payload);
  }
  /** Keyboard · `type` */
  type(payload: { text: string }): Promise<unknown> {
    return this.a.act("type", payload);
  }
  /** Keyboard · `key` */
  key(payload: { key: string }): Promise<unknown> {
    return this.a.act("key", payload);
  }
  /** Control · `wait` */
  wait(payload: { ms?: number } = {}): Promise<unknown> {
    return this.a.act("wait", payload);
  }
}

/** Physical robots driven through a robot driver (joints, gripper, drive). Each method is `act(action, payload)` on the embodiment this is bound to. */
export class RobotControls {
  constructor(private readonly a: Actor) {}
  /** Robot driver · `joint` */
  joint(payload: { name: string; value: number }): Promise<unknown> {
    return this.a.act("joint", payload);
  }
  /** Robot driver · `pose` */
  pose(payload: { pose: Args }): Promise<unknown> {
    return this.a.act("pose", payload);
  }
  /** Robot driver · `gripper` */
  gripper(payload: { value: number }): Promise<unknown> {
    return this.a.act("gripper", payload);
  }
  /** Robot driver · `home` */
  home(): Promise<unknown> {
    return this.a.act("home", {});
  }
  /** Robot driver · `reset` */
  reset(): Promise<unknown> {
    return this.a.act("reset", {});
  }
  /** Robot driver · `stop` */
  stop(): Promise<unknown> {
    return this.a.act("stop", {});
  }
  /** Robot driver · `move` */
  move(payload: { value?: number } = {}): Promise<unknown> {
    return this.a.act("move", payload);
  }
  /** Robot driver · `back` */
  back(payload: { value?: number } = {}): Promise<unknown> {
    return this.a.act("back", payload);
  }
  /** Robot driver · `turn` */
  turn(payload: { value?: number } = {}): Promise<unknown> {
    return this.a.act("turn", payload);
  }
}

/** Simulated worlds — lifecycle, interaction, and the robots inside them. Each method is `act(action, payload)` on the embodiment this is bound to. */
export class SimControls {
  constructor(private readonly a: Actor) {}
  /** Simulation lifecycle · `run` */
  run(): Promise<unknown> {
    return this.a.act("run", {});
  }
  /** Simulation lifecycle · `pause` */
  pause(): Promise<unknown> {
    return this.a.act("pause", {});
  }
  /** Simulation lifecycle · `step` */
  step(payload: { n?: number } = {}): Promise<unknown> {
    return this.a.act("step", payload);
  }
  /** Simulation lifecycle · `speed` */
  speed(payload: { x: number }): Promise<unknown> {
    return this.a.act("speed", payload);
  }
  /** Simulation lifecycle · `reset` */
  reset(): Promise<unknown> {
    return this.a.act("reset", {});
  }
  /** Simulation lifecycle · `params` */
  params(payload: { values: Args }): Promise<unknown> {
    return this.a.act("params", payload);
  }
  /** Simulation lifecycle · `load` */
  load(payload: {
    world: { name: string; kind: "simulation"; scene: Args; [key: string]: unknown };
  }): Promise<unknown> {
    return this.a.act("load", payload);
  }
  /** Simulation lifecycle · `describe` */
  describe(): Promise<unknown> {
    return this.a.act("describe", {});
  }
  /** Simulation force drag · `grab` */
  grab(payload: {
    body: string;
    local: number[];
    target: number[];
    stiffness?: number;
    damping?: number;
    max_force?: number;
    max_speed?: number;
  }): Promise<unknown> {
    return this.a.act("grab", payload);
  }
  /** Simulation force drag · `drag` */
  drag(payload: { target: number[] }): Promise<unknown> {
    return this.a.act("drag", payload);
  }
  /** Simulation force drag · `release` */
  release(): Promise<unknown> {
    return this.a.act("release", {});
  }
  /** Simulation robots · `ctrl` */
  ctrl(payload: { robotId?: string; targets: Args }): Promise<unknown> {
    return this.a.act("ctrl", payload);
  }
  /** Simulation robots · `actuator` */
  actuator(payload: { robotId?: string; name: string; value: number }): Promise<unknown> {
    return this.a.act("actuator", payload);
  }
  /** Simulation robots · `pose` */
  pose(payload: { robotId?: string; joints: Args }): Promise<unknown> {
    return this.a.act("pose", payload);
  }
  /** Simulation robots · `ik` */
  ik(payload: {
    robotId?: string;
    target: number[];
    axis?: number[];
    along?: number[];
    tolerance?: number;
  }): Promise<unknown> {
    return this.a.act("ik", payload);
  }
  /** Simulation robots · `trajectory` */
  trajectory(payload: {
    robotId?: string;
    waypoints: { at: number; targets: Args }[];
  }): Promise<unknown> {
    return this.a.act("trajectory", payload);
  }
  /** Simulation robots · `grip` */
  grip(payload: { robotId?: string; close: boolean }): Promise<unknown> {
    return this.a.act("grip", payload);
  }
  /** Simulation robots · `stop` */
  stop(payload: { robotId?: string } = {}): Promise<unknown> {
    return this.a.act("stop", payload);
  }
  /** Simulation robots · `add_robot` */
  addRobot(payload: {
    id: string;
    device: string;
    definition?: Args;
    at: number[];
    yaw?: number;
    joints?: Args;
  }): Promise<unknown> {
    return this.a.act("add_robot", payload);
  }
  /** Simulation robots · `remove_robot` */
  removeRobot(payload: { robotId?: string } = {}): Promise<unknown> {
    return this.a.act("remove_robot", payload);
  }
}

/** Where a named parameter's value comes from on a command line — see `SdkParam.cli` in the schema. */
export type CliSource = "positional" | "join" | "json" | "file" | "language" | "flag";
export interface CliParam {
  name: string;
  from?: CliSource;
  /** Coerce the value to a number. */
  number?: boolean;
}
export interface Command {
  /** Namespace name, or "" for a method on the client itself. */
  group: string;
  /** The typed-SDK method name — the CLI CALLS that method, so mapping lives in exactly one place. */
  verb: string;
  tool: string;
  /** A factory namespace's own params, bound before the verb (`commandagi social <platform> post …`). */
  factory?: { name: string; from: "positional" | "flag" }[];
  params?: CliParam[];
  /** The method takes a trailing options bag: remaining `--flags` (plus `--json`) fill it. */
  spread?: boolean;
  doc: string;
}

/** ONE ROW PER SCHEMA METHOD — generated, so the CLI cannot drift from the SDK. */
export const CLI_COMMANDS: readonly Command[] = [
  { group: "", verb: "whoami", tool: "whoami", doc: "The account this key belongs to." },
  {
    group: "",
    verb: "search",
    tool: "search_tools",
    params: [
      { name: "query", from: "join" },
      { name: "limit", from: "flag", number: true },
    ],
    doc: "Search the whole tool catalog by keyword.",
  },
  {
    group: "",
    verb: "run",
    tool: "run_code",
    params: [
      { name: "code", from: "file" },
      { name: "language", from: "language" },
      { name: "threadId", from: "flag" },
    ],
    doc: "Run a snippet server-side (JavaScript / TypeScript / Python).",
  },
  {
    group: "",
    verb: "post",
    tool: "post",
    spread: true,
    doc: "Publish a file to a connected social account.",
  },
  { group: "threads", verb: "list", tool: "list_threads", doc: "Your threads." },
  {
    group: "threads",
    verb: "get",
    tool: "get_thread",
    params: [{ name: "threadId" }],
    doc: "One thread's detail.",
  },
  {
    group: "threads",
    verb: "create",
    tool: "create_thread",
    spread: true,
    doc: "Spawn a thread: {intent, snapshotId?, …}, or {agentless: true, snapshotId} for a world you drive.",
  },
  {
    group: "threads",
    verb: "send",
    tool: "send_message",
    params: [{ name: "threadId" }, { name: "text", from: "join" }],
    doc: "Message a thread.",
  },
  {
    group: "threads",
    verb: "events",
    tool: "thread_events",
    params: [{ name: "threadId" }],
    doc: "A thread's event log.",
  },
  {
    group: "threads",
    verb: "kill",
    tool: "kill_process",
    params: [{ name: "threadId" }],
    doc: "Stop a thread's run (the thread itself persists).",
  },
  { group: "embodiments", verb: "list", tool: "list_embodiments", doc: "Attached embodiments." },
  {
    group: "embodiments",
    verb: "launch",
    tool: "launch_embodiment",
    spread: true,
    doc: "Launch an embodiment into the thread: {kind?, snapshotId?, fromSnapshotId?}.",
  },
  {
    group: "embodiments",
    verb: "observe",
    tool: "observe",
    spread: true,
    doc: "The thread's observation plane: stream channels and the latest frame per embodiment.",
  },
  {
    group: "embodiments",
    verb: "controls",
    tool: "list_controls",
    params: [{ name: "embodimentId" }, { name: "threadId", from: "flag" }],
    doc: "What an embodiment can be driven with right now: channels, actions, payload schemas.",
  },
  {
    group: "embodiments",
    verb: "act",
    tool: "act",
    params: [
      { name: "embodimentId" },
      { name: "action" },
      { name: "payload", from: "json" },
      { name: "threadId", from: "flag" },
    ],
    doc: "Drive an embodiment with one declared action (see controls).",
  },
  {
    group: "embodiments",
    verb: "describe",
    tool: "describe_world",
    params: [{ name: "threadId", from: "flag" }],
    doc: "The live sim/robot world: robots, objects and poses the runtime reports.",
  },
  {
    group: "memory",
    verb: "search",
    tool: "memory_search",
    params: [{ name: "query", from: "join" }],
    doc: "Recall by query (the drive's content index over memories/).",
  },
  {
    group: "memory",
    verb: "remember",
    tool: "memory_remember",
    spread: true,
    doc: "Write a memory file.",
  },
  {
    group: "memory",
    verb: "forget",
    tool: "memory_forget",
    params: [{ name: "path" }],
    doc: "Delete a memory file by its path.",
  },
  { group: "integrations", verb: "list", tool: "list_integrations", doc: "What's connected." },
  {
    group: "integrations",
    verb: "call",
    tool: "integration_call",
    params: [{ name: "integration" }],
    spread: true,
    doc: "Drive a provider's API (method/path/query/body).",
  },
  {
    group: "social",
    verb: "post",
    tool: "post",
    factory: [
      { name: "platform", from: "positional" },
      { name: "account", from: "flag" },
    ],
    params: [{ name: "fileId" }],
    spread: true,
    doc: "Publish a stored file to this account.",
  },
  {
    group: "social",
    verb: "call",
    tool: "integration_call",
    factory: [
      { name: "platform", from: "positional" },
      { name: "account", from: "flag" },
    ],
    params: [{ name: "method" }, { name: "path" }],
    spread: true,
    doc: "Raw API call as this account.",
  },
];
