// GENERATED by scripts/sdk/generate-sdks.mts from the CommandAGI SDK schema — do not edit by hand.
/* eslint-disable */

export type Args = Record<string, unknown>;

/** The one environment every SDK reads — and the one the platform injects where it runs your code. */
export const ENV = {
  apiKey: "COMMANDAGI_API_KEY",
  baseUrl: "COMMANDAGI_BASE_URL",
  threadId: "COMMANDAGI_THREAD_ID",
} as const;
export const DEFAULT_BASE_URL = "https://api.commandagi.com";

/** The composed, language-neutral schema every SDK is generated from. */
export const SDK_SCHEMA = {
  $comment:
    "GENERATED by scripts/sdk/generate-sdks.mts from the CommandAGI SDK schema — do not edit by hand.",
  version: 1,
  env: {
    apiKey: "COMMANDAGI_API_KEY",
    baseUrl: "COMMANDAGI_BASE_URL",
    threadId: "COMMANDAGI_THREAD_ID",
  },
  defaultBaseUrl: "https://api.commandagi.com",
  tools: {
    transport:
      "POST {baseUrl}/mcp — JSON-RPC 2.0 `tools/call` {name, arguments}, `authorization: Bearer {apiKey}`; the result's text content is JSON. `call(tool, args)` reaches ANY platform tool by name.",
    root: [
      {
        name: "constraints",
        tool: "agent_constraints",
        doc: "Inspect or impose an immutable device-action state machine for this thread's agent.",
        params: [
          {
            name: "opts",
            key: null,
            type: "object",
            required: false,
            spread: true,
            prefix: null,
            cli: "spread",
          },
        ],
        bound: {},
        withThread: true,
      },
      {
        name: "whoami",
        tool: "whoami",
        doc: "The account this key belongs to.",
        params: [],
        bound: {},
        withThread: false,
      },
      {
        name: "search",
        tool: "search_tools",
        doc: "Search the whole tool catalog by keyword.",
        params: [
          {
            name: "query",
            key: "query",
            type: "string",
            required: true,
            spread: false,
            prefix: null,
            cli: "join",
          },
          {
            name: "limit",
            key: "limit",
            type: "integer",
            required: false,
            spread: false,
            prefix: null,
            cli: "flag",
          },
        ],
        bound: {},
        withThread: false,
      },
      {
        name: "run",
        tool: "run_code",
        doc: "Run a snippet server-side (JavaScript / TypeScript / Python).",
        params: [
          {
            name: "code",
            key: "code",
            type: "string",
            required: true,
            spread: false,
            prefix: null,
            cli: "file",
          },
          {
            name: "language",
            key: "language",
            type: "string",
            required: false,
            spread: false,
            prefix: null,
            cli: "language",
          },
          {
            name: "threadId",
            key: "threadId",
            type: "string",
            required: false,
            spread: false,
            prefix: null,
            cli: "flag",
          },
        ],
        bound: {},
        withThread: true,
      },
      {
        name: "post",
        tool: "post",
        doc: "Publish a file to a connected social account.",
        params: [
          {
            name: "opts",
            key: null,
            type: "object",
            required: false,
            spread: true,
            prefix: null,
            cli: "spread",
          },
        ],
        bound: {},
        withThread: false,
      },
    ],
    namespaces: [
      {
        name: "computer",
        doc: "Computer input with per-action authority and private variable references.",
        factory: null,
        methods: [
          {
            name: "screenshot",
            tool: "computer_screenshot",
            doc: "Observe the computer's current screen.",
            params: [
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: true,
          },
          {
            name: "act",
            tool: "computer_act",
            doc: "One action/payload or an ordered actions array. Stops on first failure. Type a granted variable with text: '${env:NAME}'.",
            params: [
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: true,
          },
        ],
      },
      {
        name: "threads",
        doc: "Agent threads — the unit of work.",
        factory: null,
        methods: [
          {
            name: "list",
            tool: "list_threads",
            doc: "Your threads.",
            params: [],
            bound: {},
            withThread: false,
          },
          {
            name: "get",
            tool: "get_thread",
            doc: "One thread's detail.",
            params: [
              {
                name: "threadId",
                key: "threadId",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "create",
            tool: "create_thread",
            doc: "Spawn a thread: {intent, snapshotId?, …}, or {agentless: true, snapshotId} for a world you drive.",
            params: [
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "send",
            tool: "send_message",
            doc: "Message a thread.",
            params: [
              {
                name: "threadId",
                key: "threadId",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "text",
                key: "text",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "join",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "events",
            tool: "thread_events",
            doc: "A thread's event log.",
            params: [
              {
                name: "threadId",
                key: "threadId",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "kill",
            tool: "kill_process",
            doc: "Stop a thread's run (the thread itself persists).",
            params: [
              {
                name: "threadId",
                key: "pid",
                type: "string",
                required: true,
                spread: false,
                prefix: "thread:",
                cli: "positional",
              },
            ],
            bound: {},
            withThread: false,
          },
        ],
      },
      {
        name: "embodiments",
        doc: "Computers, cameras, robots and sims attached to a thread.",
        factory: null,
        methods: [
          {
            name: "list",
            tool: "list_embodiments",
            doc: "Attached embodiments.",
            params: [],
            bound: {},
            withThread: false,
          },
          {
            name: "launch",
            tool: "launch_embodiment",
            doc: "Launch an embodiment into the thread: {kind?, snapshotId?, fromSnapshotId?}.",
            params: [
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: true,
          },
          {
            name: "observe",
            tool: "observe",
            doc: "The thread's observation plane: stream channels and the latest frame per embodiment.",
            params: [
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: true,
          },
          {
            name: "controls",
            tool: "list_controls",
            doc: "What an embodiment can be driven with right now: channels, actions, payload schemas.",
            params: [
              {
                name: "embodimentId",
                key: "embodimentId",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "threadId",
                key: "threadId",
                type: "string",
                required: false,
                spread: false,
                prefix: null,
                cli: "flag",
              },
            ],
            bound: {},
            withThread: true,
          },
          {
            name: "act",
            tool: "act",
            doc: "Drive an embodiment with one declared action (see controls).",
            params: [
              {
                name: "embodimentId",
                key: "embodimentId",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "action",
                key: "action",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "payload",
                key: "payload",
                type: "object",
                required: false,
                spread: false,
                prefix: null,
                cli: "json",
              },
              {
                name: "threadId",
                key: "threadId",
                type: "string",
                required: false,
                spread: false,
                prefix: null,
                cli: "flag",
              },
            ],
            bound: {},
            withThread: true,
          },
          {
            name: "describe",
            tool: "describe_world",
            doc: "The live sim/robot world: robots, objects and poses the runtime reports.",
            params: [
              {
                name: "threadId",
                key: "threadId",
                type: "string",
                required: false,
                spread: false,
                prefix: null,
                cli: "flag",
              },
            ],
            bound: {},
            withThread: true,
          },
        ],
      },
      {
        name: "billing",
        doc: "Resold third-party services, charged at the provider's price (docs/billing.md).",
        factory: null,
        methods: [
          {
            name: "prices",
            tool: "quote_passthrough",
            doc: "Every pass-through price, with its source and date.",
            params: [],
            bound: {},
            withThread: false,
          },
          {
            name: "quote",
            tool: "quote_passthrough",
            doc: 'What a service costs before you buy it: {price: "twilio/us-sms", months?, units?, oneTime?}.',
            params: [
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "charges",
            tool: "list_passthrough_charges",
            doc: "The account's pass-through line items, monthly items and balance.",
            params: [
              {
                name: "limit",
                key: "limit",
                type: "integer",
                required: false,
                spread: false,
                prefix: null,
                cli: "flag",
              },
            ],
            bound: {},
            withThread: false,
          },
        ],
      },
      {
        name: "memory",
        doc: "The agent's durable memory: markdown files under memories/ in the thread's drive.",
        factory: null,
        methods: [
          {
            name: "search",
            tool: "memory_search",
            doc: "Recall by query (the drive's content index over memories/).",
            params: [
              {
                name: "query",
                key: "q",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "join",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "remember",
            tool: "memory_remember",
            doc: "Write a memory file.",
            params: [
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "forget",
            tool: "memory_forget",
            doc: "Delete a memory file by its path.",
            params: [
              {
                name: "path",
                key: "path",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
            ],
            bound: {},
            withThread: false,
          },
        ],
      },
      {
        name: "integrations",
        doc: "Connected third-party accounts.",
        factory: null,
        methods: [
          {
            name: "list",
            tool: "list_integrations",
            doc: "What's connected.",
            params: [],
            bound: {},
            withThread: false,
          },
          {
            name: "call",
            tool: "integration_call",
            doc: "Drive a provider's API (method/path/query/body).",
            params: [
              {
                name: "integration",
                key: "integration",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: false,
          },
        ],
      },
      {
        name: "web",
        doc: "Web search through many providers, one shape (docs/search.md): each result names who returned it; each call says what it cost.",
        factory: null,
        methods: [
          {
            name: "search",
            tool: "web_search",
            doc: "Search: kind search | news | academic | code | social | images | video; provider, limit, since, domains … in opts.",
            params: [
              {
                name: "query",
                key: "query",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "join",
              },
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "fetch",
            tool: "web_fetch",
            doc: "One page as clean text.",
            params: [
              {
                name: "url",
                key: "url",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "crawl",
            tool: "web_crawl",
            doc: "Many pages of one site (pages in opts).",
            params: [
              {
                name: "url",
                key: "url",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "answer",
            tool: "web_answer",
            doc: "An answer with citations; depth research for a long report.",
            params: [
              {
                name: "question",
                key: "question",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "join",
              },
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "providers",
            tool: "web_providers",
            doc: "The providers: what each offers and costs, and whether you can call it.",
            params: [],
            bound: {},
            withThread: false,
          },
        ],
      },
      {
        name: "postal",
        doc: "Paper mail (docs/postal.md): letters from a .letter.tsx and postcards from a .postcard.tsx in your files, and mailboxes that receive and scan mail.",
        factory: null,
        methods: [
          {
            name: "quote",
            tool: "postal_quote",
            doc: "What mailing the letter or postcard would cost, and how it would go (its choices: the providers that can mail it). Costs nothing.",
            params: [
              {
                name: "source",
                key: "source",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
                options: {
                  provider: {
                    type: "string",
                    enum: ["lob", "click2mail"],
                    doc: "Who prints and posts it: lob (the default; the US and every other country) or click2mail (US only). Omitted: automatic, the best provider for the destination in the account's postal.providers order, Lob first.",
                  },
                  ownerId: {
                    type: "string",
                    enum: null,
                    doc: "An organisation's id, to act for it. Omitted: your own account.",
                  },
                },
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "send",
            tool: "postal_send",
            doc: "Mail the letter or postcard: charged first, recorded before it is sent, never retried. An agent needs a postal grant.",
            params: [
              {
                name: "source",
                key: "source",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
                options: {
                  provider: {
                    type: "string",
                    enum: ["lob", "click2mail"],
                    doc: "Who prints and posts it: lob (the default; the US and every other country) or click2mail (US only). Omitted: automatic, the best provider for the destination in the account's postal.providers order, Lob first.",
                  },
                  ownerId: {
                    type: "string",
                    enum: null,
                    doc: "An organisation's id, to act for it. Omitted: your own account.",
                  },
                },
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "status",
            tool: "postal_status",
            doc: "A sent piece's state and records; without a piece, the sent pieces.",
            params: [
              {
                name: "piece",
                key: "piece",
                type: "string",
                required: false,
                spread: false,
                prefix: null,
                cli: "flag",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "cancel",
            tool: "postal_cancel",
            doc: "Cancel a piece before it is printed; the charge comes back.",
            params: [
              {
                name: "piece",
                key: "piece",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "inbox",
            tool: "postal_inbox",
            doc: "Your mailboxes, or one mailbox's received pieces with their scans.",
            params: [
              {
                name: "mailbox",
                key: "mailbox",
                type: "string",
                required: false,
                spread: false,
                prefix: null,
                cli: "flag",
              },
            ],
            bound: {},
            withThread: false,
          },
        ],
      },
      {
        name: "social",
        doc: "A single connected social account, bound: cagi.social('tiktok', '@brand').post(fileId).",
        factory: [
          {
            name: "platform",
            key: "platform",
            type: "string",
            required: true,
            spread: false,
            prefix: null,
            cli: "positional",
          },
          {
            name: "account",
            key: "account",
            type: "string",
            required: false,
            spread: false,
            prefix: null,
            cli: "flag",
          },
        ],
        methods: [
          {
            name: "post",
            tool: "post",
            doc: "Publish a stored file to this account.",
            params: [
              {
                name: "fileId",
                key: "fileId",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: { integration: "platform", account: "account" },
            withThread: false,
          },
          {
            name: "call",
            tool: "integration_call",
            doc: "Raw API call as this account.",
            params: [
              {
                name: "method",
                key: "method",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "path",
                key: "path",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: { integration: "platform", account: "account" },
            withThread: false,
          },
        ],
      },
      {
        name: "phone",
        doc: "The account's phone lines (docs/phone.md). An agent texts and calls only under a phone grant its owner made.",
        factory: null,
        methods: [
          {
            name: "lines",
            tool: "list_phone_lines",
            doc: "The lines you own or may use.",
            params: [
              {
                name: "ownerId",
                key: "ownerId",
                type: "string",
                required: false,
                spread: false,
                prefix: null,
                cli: "flag",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "conversations",
            tool: "list_phone_conversations",
            doc: "A line's conversations, newest first.",
            params: [
              {
                name: "lineId",
                key: "lineId",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "read",
            tool: "read_phone_conversation",
            doc: "One conversation's records (phone/<line>/<correspondent>.jsonl); `after` is a record id or an ISO time.",
            params: [
              {
                name: "lineId",
                key: "lineId",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "correspondent",
                key: "correspondent",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "after",
                key: "after",
                type: "string",
                required: false,
                spread: false,
                prefix: null,
                cli: "flag",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "quote",
            tool: "quote_phone_number",
            doc: "What buying a number charges now, monthly and per use. Buys nothing.",
            params: [
              {
                name: "e164",
                key: "e164",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "country",
                key: "country",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "provider",
                key: "provider",
                type: "string",
                required: false,
                spread: false,
                prefix: null,
                cli: "flag",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "text",
            tool: "send_text",
            doc: "Send a text (an MMS with drive-file media). Recorded before it is sent; never retried.",
            params: [
              {
                name: "lineId",
                key: "lineId",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "to",
                key: "to",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "body",
                key: "body",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "media",
                key: "media",
                type: "array",
                required: false,
                spread: false,
                prefix: null,
                cli: "json",
              },
            ],
            bound: {},
            withThread: false,
          },
          {
            name: "call",
            tool: "place_call",
            doc: "Click-to-call: ring the line's forward-to number (or a number your grant lists), then connect to `to`.",
            params: [
              {
                name: "lineId",
                key: "lineId",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "to",
                key: "to",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "bridgeTo",
                key: "bridgeTo",
                type: "string",
                required: false,
                spread: false,
                prefix: null,
                cli: "flag",
              },
            ],
            bound: {},
            withThread: false,
          },
        ],
      },
      {
        name: "vpn",
        doc: "The VPN overlay (docs/vpn.md): its nodes and exits, and egress from an exit's address.",
        factory: null,
        methods: [
          {
            name: "status",
            tool: "vpn_status",
            doc: "The account's nodes, the exits it may use, the ACL and the exit grants.",
            params: [],
            bound: {},
            withThread: false,
          },
          {
            name: "fetch",
            tool: "vpn_fetch",
            doc: "Fetch a URL from a VPN exit's address (method, headers, body, exit in opts); refused without an exit grant.",
            params: [
              {
                name: "url",
                key: "url",
                type: "string",
                required: true,
                spread: false,
                prefix: null,
                cli: "positional",
              },
              {
                name: "opts",
                key: null,
                type: "object",
                required: false,
                spread: true,
                prefix: null,
                cli: "spread",
              },
            ],
            bound: {},
            withThread: false,
          },
        ],
      },
    ],
  },
  session: {
    transport:
      "Frames: WebSocket {baseUrl→ws}/rt/thread/{threadId}?token={apiKey}; server messages `frame` {embodimentId, channelId, url} carry the latest image (a data: URL or an https URL fetched with the same bearer). Control: every vocabulary method is `embodiments.act(embodimentId, action, payload)` — the thread resolves the action against what that embodiment live-declares (embodiments.controls).",
    vocabularies: [
      {
        name: "desktop",
        doc: "Computers — pointer, keyboard and waits, in pixels of the latest frame (docs/computer-use.md).",
        actions: [
          {
            name: "click",
            channelId: "computer",
            label:
              "Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first.",
            schema: {
              type: "object",
              properties: {
                x: { type: "number", description: "pixel column of the latest frame", minimum: 0 },
                y: { type: "number", description: "pixel row of the latest frame", minimum: 0 },
                mods: {
                  type: "string",
                  maxLength: 40,
                  description:
                    "modifiers held during the action: shift, ctrl, alt, super, joined by +",
                },
                basis: {
                  type: "string",
                  maxLength: 10,
                  description:
                    "the id of the frame this action was planned on; refused as stale if the screen changed since",
                },
              },
              required: ["x", "y"],
              additionalProperties: false,
            },
          },
          {
            name: "double_click",
            channelId: "computer",
            label:
              "Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first.",
            schema: {
              type: "object",
              properties: {
                x: { type: "number", description: "pixel column of the latest frame", minimum: 0 },
                y: { type: "number", description: "pixel row of the latest frame", minimum: 0 },
                mods: {
                  type: "string",
                  maxLength: 40,
                  description:
                    "modifiers held during the action: shift, ctrl, alt, super, joined by +",
                },
                basis: {
                  type: "string",
                  maxLength: 10,
                  description:
                    "the id of the frame this action was planned on; refused as stale if the screen changed since",
                },
              },
              required: ["x", "y"],
              additionalProperties: false,
            },
          },
          {
            name: "triple_click",
            channelId: "computer",
            label:
              "Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first.",
            schema: {
              type: "object",
              properties: {
                x: { type: "number", description: "pixel column of the latest frame", minimum: 0 },
                y: { type: "number", description: "pixel row of the latest frame", minimum: 0 },
                mods: {
                  type: "string",
                  maxLength: 40,
                  description:
                    "modifiers held during the action: shift, ctrl, alt, super, joined by +",
                },
                basis: {
                  type: "string",
                  maxLength: 10,
                  description:
                    "the id of the frame this action was planned on; refused as stale if the screen changed since",
                },
              },
              required: ["x", "y"],
              additionalProperties: false,
            },
          },
          {
            name: "right_click",
            channelId: "computer",
            label:
              "Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first.",
            schema: {
              type: "object",
              properties: {
                x: { type: "number", description: "pixel column of the latest frame", minimum: 0 },
                y: { type: "number", description: "pixel row of the latest frame", minimum: 0 },
                mods: {
                  type: "string",
                  maxLength: 40,
                  description:
                    "modifiers held during the action: shift, ctrl, alt, super, joined by +",
                },
                basis: {
                  type: "string",
                  maxLength: 10,
                  description:
                    "the id of the frame this action was planned on; refused as stale if the screen changed since",
                },
              },
              required: ["x", "y"],
              additionalProperties: false,
            },
          },
          {
            name: "middle_click",
            channelId: "computer",
            label:
              "Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first.",
            schema: {
              type: "object",
              properties: {
                x: { type: "number", description: "pixel column of the latest frame", minimum: 0 },
                y: { type: "number", description: "pixel row of the latest frame", minimum: 0 },
                mods: {
                  type: "string",
                  maxLength: 40,
                  description:
                    "modifiers held during the action: shift, ctrl, alt, super, joined by +",
                },
                basis: {
                  type: "string",
                  maxLength: 10,
                  description:
                    "the id of the frame this action was planned on; refused as stale if the screen changed since",
                },
              },
              required: ["x", "y"],
              additionalProperties: false,
            },
          },
          {
            name: "move",
            channelId: "computer",
            label:
              "Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first.",
            schema: {
              type: "object",
              properties: {
                x: { type: "number", description: "pixel column of the latest frame", minimum: 0 },
                y: { type: "number", description: "pixel row of the latest frame", minimum: 0 },
                basis: {
                  type: "string",
                  maxLength: 10,
                  description:
                    "the id of the frame this action was planned on; refused as stale if the screen changed since",
                },
              },
              required: ["x", "y"],
              additionalProperties: false,
            },
          },
          {
            name: "drag",
            channelId: "computer",
            label:
              "Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first.",
            schema: {
              type: "object",
              properties: {
                x: { type: "number", description: "pixel column of the latest frame", minimum: 0 },
                y: { type: "number", description: "pixel row of the latest frame", minimum: 0 },
                toX: {
                  type: "number",
                  description: "pixel column of the latest frame",
                  minimum: 0,
                },
                toY: { type: "number", description: "pixel row of the latest frame", minimum: 0 },
                mods: {
                  type: "string",
                  maxLength: 40,
                  description:
                    "modifiers held during the action: shift, ctrl, alt, super, joined by +",
                },
                basis: {
                  type: "string",
                  maxLength: 10,
                  description:
                    "the id of the frame this action was planned on; refused as stale if the screen changed since",
                },
              },
              required: ["x", "y", "toX", "toY"],
              additionalProperties: false,
            },
          },
          {
            name: "scroll",
            channelId: "computer",
            label:
              "Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first.",
            schema: {
              type: "object",
              properties: {
                x: { type: "number", description: "pixel column of the latest frame", minimum: 0 },
                y: { type: "number", description: "pixel row of the latest frame", minimum: 0 },
                dx: { type: "integer", minimum: -50, maximum: 50 },
                dy: {
                  type: "integer",
                  minimum: -50,
                  maximum: 50,
                  description: "wheel notches; positive scrolls down",
                },
                mods: {
                  type: "string",
                  maxLength: 40,
                  description:
                    "modifiers held during the action: shift, ctrl, alt, super, joined by +",
                },
                basis: {
                  type: "string",
                  maxLength: 10,
                  description:
                    "the id of the frame this action was planned on; refused as stale if the screen changed since",
                },
              },
              required: [],
              additionalProperties: false,
            },
          },
          {
            name: "mouse_down",
            channelId: "computer",
            label:
              "Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first.",
            schema: {
              type: "object",
              properties: {
                x: { type: "number", description: "pixel column of the latest frame", minimum: 0 },
                y: { type: "number", description: "pixel row of the latest frame", minimum: 0 },
                button: {
                  type: "string",
                  enum: ["left", "right", "middle"],
                  description:
                    "the button (default left); it stays down until mouse_up, and stop releases it",
                },
                basis: {
                  type: "string",
                  maxLength: 10,
                  description:
                    "the id of the frame this action was planned on; refused as stale if the screen changed since",
                },
              },
              required: [],
              additionalProperties: false,
            },
          },
          {
            name: "mouse_up",
            channelId: "computer",
            label:
              "Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first.",
            schema: {
              type: "object",
              properties: {
                x: { type: "number", description: "pixel column of the latest frame", minimum: 0 },
                y: { type: "number", description: "pixel row of the latest frame", minimum: 0 },
                button: {
                  type: "string",
                  enum: ["left", "right", "middle"],
                  description:
                    "the button (default left); it stays down until mouse_up, and stop releases it",
                },
                basis: {
                  type: "string",
                  maxLength: 10,
                  description:
                    "the id of the frame this action was planned on; refused as stale if the screen changed since",
                },
              },
              required: [],
              additionalProperties: false,
            },
          },
          {
            name: "key",
            channelId: "computer",
            label:
              "Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first.",
            schema: {
              type: "object",
              properties: {
                key: {
                  type: "string",
                  minLength: 1,
                  maxLength: 64,
                  description: "a key or a combo: enter, ctrl+l, ctrl+shift+t",
                },
                basis: {
                  type: "string",
                  maxLength: 10,
                  description:
                    "the id of the frame this action was planned on; refused as stale if the screen changed since",
                },
              },
              required: ["key"],
              additionalProperties: false,
            },
          },
          {
            name: "type",
            channelId: "computer",
            label:
              "Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first.",
            schema: {
              type: "object",
              properties: {
                text: { type: "string", minLength: 1, maxLength: 500 },
                textRef: {
                  type: "string",
                  pattern: "^\\$\\{env:[A-Za-z_][A-Za-z0-9_]*\\}$",
                  description: "private input reference; records keep this instead of text",
                },
                basis: {
                  type: "string",
                  maxLength: 10,
                  description:
                    "the id of the frame this action was planned on; refused as stale if the screen changed since",
                },
              },
              required: ["text"],
              additionalProperties: false,
            },
          },
          {
            name: "wait",
            channelId: "computer",
            label:
              "Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first.",
            schema: {
              type: "object",
              properties: { ms: { type: "integer", minimum: 0, maximum: 10000 } },
              required: [],
              additionalProperties: false,
            },
          },
        ],
      },
      {
        name: "robot",
        doc: "Physical robots driven through a robot driver (joints, gripper, drive).",
        actions: [
          {
            name: "joint",
            channelId: "ctrl",
            label: "Robot driver",
            schema: {
              type: "object",
              properties: {
                name: { type: "string", minLength: 1, maxLength: 256 },
                value: { type: "number", minimum: -1, maximum: 1 },
              },
              required: ["name", "value"],
              additionalProperties: false,
            },
          },
          {
            name: "pose",
            channelId: "ctrl",
            label: "Robot driver",
            schema: {
              type: "object",
              properties: { pose: { type: "object", additionalProperties: true } },
              required: ["pose"],
              additionalProperties: false,
            },
          },
          {
            name: "gripper",
            channelId: "ctrl",
            label: "Robot driver",
            schema: {
              type: "object",
              properties: { value: { type: "number", minimum: -1, maximum: 1 } },
              required: ["value"],
              additionalProperties: false,
            },
          },
          {
            name: "home",
            channelId: "ctrl",
            label: "Robot driver",
            schema: { type: "object", additionalProperties: false },
          },
          {
            name: "reset",
            channelId: "ctrl",
            label: "Robot driver",
            schema: { type: "object", additionalProperties: false },
          },
          {
            name: "stop",
            channelId: "ctrl",
            label: "Robot driver",
            schema: { type: "object", additionalProperties: false },
          },
          {
            name: "move",
            channelId: "ctrl",
            label: "Robot driver",
            schema: {
              type: "object",
              properties: { value: { type: "number", minimum: -1, maximum: 1 } },
              additionalProperties: false,
            },
          },
          {
            name: "back",
            channelId: "ctrl",
            label: "Robot driver",
            schema: {
              type: "object",
              properties: { value: { type: "number", minimum: -1, maximum: 1 } },
              additionalProperties: false,
            },
          },
          {
            name: "turn",
            channelId: "ctrl",
            label: "Robot driver",
            schema: {
              type: "object",
              properties: { value: { type: "number", minimum: -1, maximum: 1 } },
              additionalProperties: false,
            },
          },
        ],
      },
      {
        name: "sim",
        doc: "Simulated worlds — lifecycle, interaction, and the robots inside them.",
        actions: [
          {
            name: "run",
            channelId: "ctrl",
            label: "Simulation lifecycle",
            schema: { type: "object", additionalProperties: false },
          },
          {
            name: "pause",
            channelId: "ctrl",
            label: "Simulation lifecycle",
            schema: { type: "object", additionalProperties: false },
          },
          {
            name: "step",
            channelId: "ctrl",
            label: "Simulation lifecycle",
            schema: {
              type: "object",
              properties: { n: { type: "integer", minimum: 1, maximum: 100000 } },
              additionalProperties: false,
            },
          },
          {
            name: "speed",
            channelId: "ctrl",
            label: "Simulation lifecycle",
            schema: {
              type: "object",
              properties: { x: { type: "number", minimum: 0, maximum: 64 } },
              required: ["x"],
              additionalProperties: false,
            },
          },
          {
            name: "reset",
            channelId: "ctrl",
            label: "Simulation lifecycle",
            schema: { type: "object", additionalProperties: false },
          },
          {
            name: "params",
            channelId: "ctrl",
            label: "Simulation lifecycle",
            schema: {
              type: "object",
              properties: { values: { type: "object", additionalProperties: true } },
              required: ["values"],
              additionalProperties: false,
            },
          },
          {
            name: "load",
            channelId: "ctrl",
            label: "Simulation lifecycle",
            schema: {
              type: "object",
              properties: {
                world: {
                  type: "object",
                  properties: {
                    name: { type: "string", minLength: 1, maxLength: 1024 },
                    kind: { type: "string", enum: ["simulation"] },
                    scene: { type: "object", additionalProperties: true },
                  },
                  required: ["name", "kind", "scene"],
                  additionalProperties: true,
                },
              },
              required: ["world"],
              additionalProperties: false,
            },
          },
          {
            name: "describe",
            channelId: "ctrl",
            label: "Simulation lifecycle",
            schema: { type: "object", additionalProperties: false },
          },
          {
            name: "grab",
            channelId: "ctrl",
            label: "Simulation force drag",
            schema: {
              type: "object",
              properties: {
                body: { type: "string", minLength: 1, maxLength: 1024 },
                local: {
                  type: "array",
                  minItems: 3,
                  maxItems: 3,
                  items: { type: "number", minimum: -1000000000, maximum: 1000000000 },
                },
                target: {
                  type: "array",
                  minItems: 3,
                  maxItems: 3,
                  items: { type: "number", minimum: -1000000000, maximum: 1000000000 },
                },
                stiffness: { type: "number", minimum: 0, maximum: 1000000000 },
                damping: { type: "number", minimum: 0, maximum: 1000000000 },
                max_force: { type: "number", minimum: 0, maximum: 1000000000 },
                max_speed: { type: "number", minimum: 0, maximum: 1000000 },
              },
              required: ["body", "local", "target"],
              additionalProperties: false,
            },
          },
          {
            name: "drag",
            channelId: "ctrl",
            label: "Simulation force drag",
            schema: {
              type: "object",
              properties: {
                target: {
                  type: "array",
                  minItems: 3,
                  maxItems: 3,
                  items: { type: "number", minimum: -1000000000, maximum: 1000000000 },
                },
              },
              required: ["target"],
              additionalProperties: false,
            },
          },
          {
            name: "release",
            channelId: "ctrl",
            label: "Simulation force drag",
            schema: { type: "object", additionalProperties: false },
          },
          {
            name: "ctrl",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: {
                robotId: { type: "string", minLength: 1, maxLength: 1024 },
                targets: { type: "object", additionalProperties: true },
              },
              required: ["targets"],
              additionalProperties: false,
            },
          },
          {
            name: "actuator",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: {
                robotId: { type: "string", minLength: 1, maxLength: 1024 },
                name: { type: "string", minLength: 1, maxLength: 1024 },
                value: { type: "number", minimum: -1000000000, maximum: 1000000000 },
              },
              required: ["name", "value"],
              additionalProperties: false,
            },
          },
          {
            name: "pose",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: {
                robotId: { type: "string", minLength: 1, maxLength: 1024 },
                joints: { type: "object", additionalProperties: true },
              },
              required: ["joints"],
              additionalProperties: false,
            },
          },
          {
            name: "ik",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: {
                robotId: { type: "string", minLength: 1, maxLength: 1024 },
                target: {
                  type: "array",
                  minItems: 3,
                  maxItems: 3,
                  items: { type: "number", minimum: -1000000000, maximum: 1000000000 },
                },
                axis: {
                  type: "array",
                  minItems: 3,
                  maxItems: 3,
                  items: { type: "number", minimum: -1000000000, maximum: 1000000000 },
                },
                along: {
                  type: "array",
                  minItems: 3,
                  maxItems: 3,
                  items: { type: "number", minimum: -1000000000, maximum: 1000000000 },
                },
                tolerance: { type: "number", minimum: 0, maximum: 1 },
              },
              required: ["target"],
              additionalProperties: false,
            },
          },
          {
            name: "trajectory",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: {
                robotId: { type: "string", minLength: 1, maxLength: 1024 },
                waypoints: {
                  type: "array",
                  minItems: 1,
                  maxItems: 10000,
                  items: {
                    type: "object",
                    properties: {
                      at: { type: "number", minimum: 0, maximum: 1000000 },
                      targets: { type: "object", additionalProperties: true },
                    },
                    required: ["at", "targets"],
                    additionalProperties: false,
                  },
                },
              },
              required: ["waypoints"],
              additionalProperties: false,
            },
          },
          {
            name: "grip",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: {
                robotId: { type: "string", minLength: 1, maxLength: 1024 },
                close: { type: "boolean" },
              },
              required: ["close"],
              additionalProperties: false,
            },
          },
          {
            name: "stop",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: { robotId: { type: "string", minLength: 1, maxLength: 1024 } },
              additionalProperties: false,
            },
          },
          {
            name: "add_robot",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: {
                id: { type: "string", minLength: 1, maxLength: 48 },
                device: { type: "string", minLength: 1, maxLength: 1024 },
                definition: { type: "object", additionalProperties: true },
                at: {
                  type: "array",
                  minItems: 3,
                  maxItems: 3,
                  items: { type: "number", minimum: -1000000000, maximum: 1000000000 },
                },
                yaw: { type: "number", minimum: -1000000000, maximum: 1000000000 },
                joints: { type: "object", additionalProperties: true },
              },
              required: ["id", "device", "at"],
              additionalProperties: false,
            },
          },
          {
            name: "remove_robot",
            channelId: "ctrl",
            label: "Simulation robots",
            schema: {
              type: "object",
              properties: { robotId: { type: "string", minLength: 1, maxLength: 1024 } },
              additionalProperties: false,
            },
          },
        ],
      },
    ],
  },
} as const;

export interface Transport {
  call<T = unknown>(tool: string, args?: Args): Promise<T>;
  withThread(args: Args): Args;
}

/** Anything that can send one control action to one embodiment (a live Session). */
export interface Actor {
  act(action: string, payload: Args): Promise<unknown>;
}

/** Drop absent values: a tool distinguishes an omitted key from an explicit null. */
function prune(a: Args): Args {
  const out: Args = {};
  for (const [k, v] of Object.entries(a)) if (v !== undefined && v !== null) out[k] = v;
  return out;
}

/** Computer input with per-action authority and private variable references. */
export class Computer {
  constructor(private readonly t: Transport) {}
  /** Observe the computer's current screen. */
  screenshot(opts: Args = {}): Promise<unknown> {
    return this.t.call("computer_screenshot", this.t.withThread({ ...opts }));
  }
  /** One action/payload or an ordered actions array. Stops on first failure. Type a granted variable with text: '${env:NAME}'. */
  act(opts: Args = {}): Promise<unknown> {
    return this.t.call("computer_act", this.t.withThread({ ...opts }));
  }
}

/** Agent threads — the unit of work. */
export class Threads {
  constructor(private readonly t: Transport) {}
  /** Your threads. */
  list(): Promise<unknown> {
    return this.t.call("list_threads", {});
  }
  /** One thread's detail. */
  get(threadId: string): Promise<unknown> {
    return this.t.call("get_thread", prune({ threadId: threadId }));
  }
  /** Spawn a thread: {intent, snapshotId?, …}, or {agentless: true, snapshotId} for a world you drive. */
  create(opts: Args = {}): Promise<unknown> {
    return this.t.call("create_thread", { ...opts });
  }
  /** Message a thread. */
  send(threadId: string, text: string): Promise<unknown> {
    return this.t.call("send_message", prune({ threadId: threadId, text: text }));
  }
  /** A thread's event log. */
  events(threadId: string): Promise<unknown> {
    return this.t.call("thread_events", prune({ threadId: threadId }));
  }
  /** Stop a thread's run (the thread itself persists). */
  kill(threadId: string): Promise<unknown> {
    return this.t.call(
      "kill_process",
      prune({ pid: threadId == null ? undefined : "thread:" + threadId }),
    );
  }
}

/** Computers, cameras, robots and sims attached to a thread. */
export class Embodiments {
  constructor(private readonly t: Transport) {}
  /** Attached embodiments. */
  list(): Promise<unknown> {
    return this.t.call("list_embodiments", {});
  }
  /** Launch an embodiment into the thread: {kind?, snapshotId?, fromSnapshotId?}. */
  launch(opts: Args = {}): Promise<unknown> {
    return this.t.call("launch_embodiment", this.t.withThread({ ...opts }));
  }
  /** The thread's observation plane: stream channels and the latest frame per embodiment. */
  observe(opts: Args = {}): Promise<unknown> {
    return this.t.call("observe", this.t.withThread({ ...opts }));
  }
  /** What an embodiment can be driven with right now: channels, actions, payload schemas. */
  controls(embodimentId: string, threadId?: string): Promise<unknown> {
    return this.t.call(
      "list_controls",
      this.t.withThread(prune({ embodimentId: embodimentId, threadId: threadId })),
    );
  }
  /** Drive an embodiment with one declared action (see controls). */
  act(embodimentId: string, action: string, payload?: Args, threadId?: string): Promise<unknown> {
    return this.t.call(
      "act",
      this.t.withThread(
        prune({ embodimentId: embodimentId, action: action, payload: payload, threadId: threadId }),
      ),
    );
  }
  /** The live sim/robot world: robots, objects and poses the runtime reports. */
  describe(threadId?: string): Promise<unknown> {
    return this.t.call("describe_world", this.t.withThread(prune({ threadId: threadId })));
  }
}

/** Resold third-party services, charged at the provider's price (docs/billing.md). */
export class Billing {
  constructor(private readonly t: Transport) {}
  /** Every pass-through price, with its source and date. */
  prices(): Promise<unknown> {
    return this.t.call("quote_passthrough", {});
  }
  /** What a service costs before you buy it: {price: "twilio/us-sms", months?, units?, oneTime?}. */
  quote(opts: Args = {}): Promise<unknown> {
    return this.t.call("quote_passthrough", { ...opts });
  }
  /** The account's pass-through line items, monthly items and balance. */
  charges(limit?: number): Promise<unknown> {
    return this.t.call("list_passthrough_charges", prune({ limit: limit }));
  }
}

/** The agent's durable memory: markdown files under memories/ in the thread's drive. */
export class Memory {
  constructor(private readonly t: Transport) {}
  /** Recall by query (the drive's content index over memories/). */
  search(query: string): Promise<unknown> {
    return this.t.call("memory_search", prune({ q: query }));
  }
  /** Write a memory file. */
  remember(opts: Args = {}): Promise<unknown> {
    return this.t.call("memory_remember", { ...opts });
  }
  /** Delete a memory file by its path. */
  forget(path: string): Promise<unknown> {
    return this.t.call("memory_forget", prune({ path: path }));
  }
}

/** Connected third-party accounts. */
export class Integrations {
  constructor(private readonly t: Transport) {}
  /** What's connected. */
  list(): Promise<unknown> {
    return this.t.call("list_integrations", {});
  }
  /** Drive a provider's API (method/path/query/body). */
  call(integration: string, opts: Args = {}): Promise<unknown> {
    return this.t.call("integration_call", { ...prune({ integration: integration }), ...opts });
  }
}

/** Web search through many providers, one shape (docs/search.md): each result names who returned it; each call says what it cost. */
export class Web {
  constructor(private readonly t: Transport) {}
  /** Search: kind search | news | academic | code | social | images | video; provider, limit, since, domains … in opts. */
  search(query: string, opts: Args = {}): Promise<unknown> {
    return this.t.call("web_search", { ...prune({ query: query }), ...opts });
  }
  /** One page as clean text. */
  fetch(url: string, opts: Args = {}): Promise<unknown> {
    return this.t.call("web_fetch", { ...prune({ url: url }), ...opts });
  }
  /** Many pages of one site (pages in opts). */
  crawl(url: string, opts: Args = {}): Promise<unknown> {
    return this.t.call("web_crawl", { ...prune({ url: url }), ...opts });
  }
  /** An answer with citations; depth research for a long report. */
  answer(question: string, opts: Args = {}): Promise<unknown> {
    return this.t.call("web_answer", { ...prune({ question: question }), ...opts });
  }
  /** The providers: what each offers and costs, and whether you can call it. */
  providers(): Promise<unknown> {
    return this.t.call("web_providers", {});
  }
}

/** The options of `postal.quote`. */
export interface PostalQuoteOptions {
  /** Who prints and posts it: lob (the default; the US and every other country) or click2mail (US only). Omitted: automatic, the best provider for the destination in the account's postal.providers order, Lob first. */
  provider?: "lob" | "click2mail";
  /** An organisation's id, to act for it. Omitted: your own account. */
  ownerId?: string;
}

/** The options of `postal.send`. */
export interface PostalSendOptions {
  /** Who prints and posts it: lob (the default; the US and every other country) or click2mail (US only). Omitted: automatic, the best provider for the destination in the account's postal.providers order, Lob first. */
  provider?: "lob" | "click2mail";
  /** An organisation's id, to act for it. Omitted: your own account. */
  ownerId?: string;
}

/** Paper mail (docs/postal.md): letters from a .letter.tsx and postcards from a .postcard.tsx in your files, and mailboxes that receive and scan mail. */
export class Postal {
  constructor(private readonly t: Transport) {}
  /** What mailing the letter or postcard would cost, and how it would go (its choices: the providers that can mail it). Costs nothing. */
  quote(source: string, opts: PostalQuoteOptions = {}): Promise<unknown> {
    return this.t.call("postal_quote", { ...prune({ source: source }), ...opts });
  }
  /** Mail the letter or postcard: charged first, recorded before it is sent, never retried. An agent needs a postal grant. */
  send(source: string, opts: PostalSendOptions = {}): Promise<unknown> {
    return this.t.call("postal_send", { ...prune({ source: source }), ...opts });
  }
  /** A sent piece's state and records; without a piece, the sent pieces. */
  status(piece?: string): Promise<unknown> {
    return this.t.call("postal_status", prune({ piece: piece }));
  }
  /** Cancel a piece before it is printed; the charge comes back. */
  cancel(piece: string): Promise<unknown> {
    return this.t.call("postal_cancel", prune({ piece: piece }));
  }
  /** Your mailboxes, or one mailbox's received pieces with their scans. */
  inbox(mailbox?: string): Promise<unknown> {
    return this.t.call("postal_inbox", prune({ mailbox: mailbox }));
  }
}

/** A single connected social account, bound: cagi.social('tiktok', '@brand').post(fileId). */
export class Social {
  constructor(
    private readonly t: Transport,
    readonly platform: string,
    readonly account?: string,
  ) {}
  /** Publish a stored file to this account. */
  post(fileId: string, opts: Args = {}): Promise<unknown> {
    return this.t.call("post", {
      ...prune({ integration: this.platform, account: this.account, fileId: fileId }),
      ...opts,
    });
  }
  /** Raw API call as this account. */
  call(method: string, path: string, opts: Args = {}): Promise<unknown> {
    return this.t.call("integration_call", {
      ...prune({ integration: this.platform, account: this.account, method: method, path: path }),
      ...opts,
    });
  }
}

/** The account's phone lines (docs/phone.md). An agent texts and calls only under a phone grant its owner made. */
export class Phone {
  constructor(private readonly t: Transport) {}
  /** The lines you own or may use. */
  lines(ownerId?: string): Promise<unknown> {
    return this.t.call("list_phone_lines", prune({ ownerId: ownerId }));
  }
  /** A line's conversations, newest first. */
  conversations(lineId: string): Promise<unknown> {
    return this.t.call("list_phone_conversations", prune({ lineId: lineId }));
  }
  /** One conversation's records (phone/<line>/<correspondent>.jsonl); `after` is a record id or an ISO time. */
  read(lineId: string, correspondent: string, after?: string): Promise<unknown> {
    return this.t.call(
      "read_phone_conversation",
      prune({ lineId: lineId, correspondent: correspondent, after: after }),
    );
  }
  /** What buying a number charges now, monthly and per use. Buys nothing. */
  quote(e164: string, country: string, provider?: string): Promise<unknown> {
    return this.t.call(
      "quote_phone_number",
      prune({ e164: e164, country: country, provider: provider }),
    );
  }
  /** Send a text (an MMS with drive-file media). Recorded before it is sent; never retried. */
  text(lineId: string, to: string, body: string, media?: unknown[]): Promise<unknown> {
    return this.t.call("send_text", prune({ lineId: lineId, to: to, body: body, media: media }));
  }
  /** Click-to-call: ring the line's forward-to number (or a number your grant lists), then connect to `to`. */
  call(lineId: string, to: string, bridgeTo?: string): Promise<unknown> {
    return this.t.call("place_call", prune({ lineId: lineId, to: to, bridgeTo: bridgeTo }));
  }
}

/** The VPN overlay (docs/vpn.md): its nodes and exits, and egress from an exit's address. */
export class Vpn {
  constructor(private readonly t: Transport) {}
  /** The account's nodes, the exits it may use, the ACL and the exit grants. */
  status(): Promise<unknown> {
    return this.t.call("vpn_status", {});
  }
  /** Fetch a URL from a VPN exit's address (method, headers, body, exit in opts); refused without an exit grant. */
  fetch(url: string, opts: Args = {}): Promise<unknown> {
    return this.t.call("vpn_fetch", { ...prune({ url: url }), ...opts });
  }
}

/**
 * Everything above the transport. The hand-written client (./client.ts) implements `call` over
 * /mcp and `withThread`; every method here is sugar over those two.
 */
export abstract class GeneratedClient implements Transport {
  abstract call<T = unknown>(tool: string, args?: Args): Promise<T>;
  abstract withThread(args: Args): Args;
  /** Computer input with per-action authority and private variable references. */
  readonly computer = new Computer(this);
  /** Agent threads — the unit of work. */
  readonly threads = new Threads(this);
  /** Computers, cameras, robots and sims attached to a thread. */
  readonly embodiments = new Embodiments(this);
  /** Resold third-party services, charged at the provider's price (docs/billing.md). */
  readonly billing = new Billing(this);
  /** The agent's durable memory: markdown files under memories/ in the thread's drive. */
  readonly memory = new Memory(this);
  /** Connected third-party accounts. */
  readonly integrations = new Integrations(this);
  /** Web search through many providers, one shape (docs/search.md): each result names who returned it; each call says what it cost. */
  readonly web = new Web(this);
  /** Paper mail (docs/postal.md): letters from a .letter.tsx and postcards from a .postcard.tsx in your files, and mailboxes that receive and scan mail. */
  readonly postal = new Postal(this);
  /** The account's phone lines (docs/phone.md). An agent texts and calls only under a phone grant its owner made. */
  readonly phone = new Phone(this);
  /** The VPN overlay (docs/vpn.md): its nodes and exits, and egress from an exit's address. */
  readonly vpn = new Vpn(this);
  /** A single connected social account, bound: cagi.social('tiktok', '@brand').post(fileId). */
  social(platform: string, account?: string): Social {
    return new Social(this, platform, account);
  }
  /** Inspect or impose an immutable device-action state machine for this thread's agent. */
  constraints(opts: Args = {}): Promise<unknown> {
    return this.call("agent_constraints", this.withThread({ ...opts }));
  }
  /** The account this key belongs to. */
  whoami(): Promise<unknown> {
    return this.call("whoami", {});
  }
  /** Search the whole tool catalog by keyword. */
  search(query: string, limit?: number): Promise<unknown> {
    return this.call("search_tools", prune({ query: query, limit: limit }));
  }
  /** Run a snippet server-side (JavaScript / TypeScript / Python). */
  run(code: string, language?: string, threadId?: string): Promise<unknown> {
    return this.call(
      "run_code",
      this.withThread(prune({ code: code, language: language, threadId: threadId })),
    );
  }
  /** Publish a file to a connected social account. */
  post(opts: Args = {}): Promise<unknown> {
    return this.call("post", { ...opts });
  }
}

/** Computers — pointer, keyboard and waits, in pixels of the latest frame (docs/computer-use.md). Each method is `act(action, payload)` on the embodiment this is bound to. */
export class DesktopControls {
  constructor(private readonly a: Actor) {}
  /** Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first. · `click` */
  click(payload: { x: number; y: number; mods?: string; basis?: string }): Promise<unknown> {
    return this.a.act("click", payload);
  }
  /** Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first. · `double_click` */
  doubleClick(payload: { x: number; y: number; mods?: string; basis?: string }): Promise<unknown> {
    return this.a.act("double_click", payload);
  }
  /** Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first. · `triple_click` */
  tripleClick(payload: { x: number; y: number; mods?: string; basis?: string }): Promise<unknown> {
    return this.a.act("triple_click", payload);
  }
  /** Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first. · `right_click` */
  rightClick(payload: { x: number; y: number; mods?: string; basis?: string }): Promise<unknown> {
    return this.a.act("right_click", payload);
  }
  /** Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first. · `middle_click` */
  middleClick(payload: { x: number; y: number; mods?: string; basis?: string }): Promise<unknown> {
    return this.a.act("middle_click", payload);
  }
  /** Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first. · `move` */
  move(payload: { x: number; y: number; basis?: string }): Promise<unknown> {
    return this.a.act("move", payload);
  }
  /** Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first. · `drag` */
  drag(payload: {
    x: number;
    y: number;
    toX: number;
    toY: number;
    mods?: string;
    basis?: string;
  }): Promise<unknown> {
    return this.a.act("drag", payload);
  }
  /** Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first. · `scroll` */
  scroll(
    payload: {
      x?: number;
      y?: number;
      dx?: number;
      dy?: number;
      mods?: string;
      basis?: string;
    } = {},
  ): Promise<unknown> {
    return this.a.act("scroll", payload);
  }
  /** Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first. · `mouse_down` */
  mouseDown(
    payload: { x?: number; y?: number; button?: "left" | "right" | "middle"; basis?: string } = {},
  ): Promise<unknown> {
    return this.a.act("mouse_down", payload);
  }
  /** Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first. · `mouse_up` */
  mouseUp(
    payload: { x?: number; y?: number; button?: "left" | "right" | "middle"; basis?: string } = {},
  ): Promise<unknown> {
    return this.a.act("mouse_up", payload);
  }
  /** Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first. · `key` */
  key(payload: { key: string; basis?: string }): Promise<unknown> {
    return this.a.act("key", payload);
  }
  /** Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first. · `type` */
  type(payload: { text: string; textRef?: string; basis?: string }): Promise<unknown> {
    return this.a.act("type", payload);
  }
  /** Computer. Coordinates are pixels of the latest frame of this computer (0,0 top left); take a screenshot first. · `wait` */
  wait(payload: { ms?: number } = {}): Promise<unknown> {
    return this.a.act("wait", payload);
  }
}

/** Physical robots driven through a robot driver (joints, gripper, drive). Each method is `act(action, payload)` on the embodiment this is bound to. */
export class RobotControls {
  constructor(private readonly a: Actor) {}
  /** Robot driver · `joint` */
  joint(payload: { name: string; value: number }): Promise<unknown> {
    return this.a.act("joint", payload);
  }
  /** Robot driver · `pose` */
  pose(payload: { pose: Args }): Promise<unknown> {
    return this.a.act("pose", payload);
  }
  /** Robot driver · `gripper` */
  gripper(payload: { value: number }): Promise<unknown> {
    return this.a.act("gripper", payload);
  }
  /** Robot driver · `home` */
  home(): Promise<unknown> {
    return this.a.act("home", {});
  }
  /** Robot driver · `reset` */
  reset(): Promise<unknown> {
    return this.a.act("reset", {});
  }
  /** Robot driver · `stop` */
  stop(): Promise<unknown> {
    return this.a.act("stop", {});
  }
  /** Robot driver · `move` */
  move(payload: { value?: number } = {}): Promise<unknown> {
    return this.a.act("move", payload);
  }
  /** Robot driver · `back` */
  back(payload: { value?: number } = {}): Promise<unknown> {
    return this.a.act("back", payload);
  }
  /** Robot driver · `turn` */
  turn(payload: { value?: number } = {}): Promise<unknown> {
    return this.a.act("turn", payload);
  }
}

/** Simulated worlds — lifecycle, interaction, and the robots inside them. Each method is `act(action, payload)` on the embodiment this is bound to. */
export class SimControls {
  constructor(private readonly a: Actor) {}
  /** Simulation lifecycle · `run` */
  run(): Promise<unknown> {
    return this.a.act("run", {});
  }
  /** Simulation lifecycle · `pause` */
  pause(): Promise<unknown> {
    return this.a.act("pause", {});
  }
  /** Simulation lifecycle · `step` */
  step(payload: { n?: number } = {}): Promise<unknown> {
    return this.a.act("step", payload);
  }
  /** Simulation lifecycle · `speed` */
  speed(payload: { x: number }): Promise<unknown> {
    return this.a.act("speed", payload);
  }
  /** Simulation lifecycle · `reset` */
  reset(): Promise<unknown> {
    return this.a.act("reset", {});
  }
  /** Simulation lifecycle · `params` */
  params(payload: { values: Args }): Promise<unknown> {
    return this.a.act("params", payload);
  }
  /** Simulation lifecycle · `load` */
  load(payload: {
    world: { name: string; kind: "simulation"; scene: Args; [key: string]: unknown };
  }): Promise<unknown> {
    return this.a.act("load", payload);
  }
  /** Simulation lifecycle · `describe` */
  describe(): Promise<unknown> {
    return this.a.act("describe", {});
  }
  /** Simulation force drag · `grab` */
  grab(payload: {
    body: string;
    local: number[];
    target: number[];
    stiffness?: number;
    damping?: number;
    max_force?: number;
    max_speed?: number;
  }): Promise<unknown> {
    return this.a.act("grab", payload);
  }
  /** Simulation force drag · `drag` */
  drag(payload: { target: number[] }): Promise<unknown> {
    return this.a.act("drag", payload);
  }
  /** Simulation force drag · `release` */
  release(): Promise<unknown> {
    return this.a.act("release", {});
  }
  /** Simulation robots · `ctrl` */
  ctrl(payload: { robotId?: string; targets: Args }): Promise<unknown> {
    return this.a.act("ctrl", payload);
  }
  /** Simulation robots · `actuator` */
  actuator(payload: { robotId?: string; name: string; value: number }): Promise<unknown> {
    return this.a.act("actuator", payload);
  }
  /** Simulation robots · `pose` */
  pose(payload: { robotId?: string; joints: Args }): Promise<unknown> {
    return this.a.act("pose", payload);
  }
  /** Simulation robots · `ik` */
  ik(payload: {
    robotId?: string;
    target: number[];
    axis?: number[];
    along?: number[];
    tolerance?: number;
  }): Promise<unknown> {
    return this.a.act("ik", payload);
  }
  /** Simulation robots · `trajectory` */
  trajectory(payload: {
    robotId?: string;
    waypoints: { at: number; targets: Args }[];
  }): Promise<unknown> {
    return this.a.act("trajectory", payload);
  }
  /** Simulation robots · `grip` */
  grip(payload: { robotId?: string; close: boolean }): Promise<unknown> {
    return this.a.act("grip", payload);
  }
  /** Simulation robots · `stop` */
  stop(payload: { robotId?: string } = {}): Promise<unknown> {
    return this.a.act("stop", payload);
  }
  /** Simulation robots · `add_robot` */
  addRobot(payload: {
    id: string;
    device: string;
    definition?: Args;
    at: number[];
    yaw?: number;
    joints?: Args;
  }): Promise<unknown> {
    return this.a.act("add_robot", payload);
  }
  /** Simulation robots · `remove_robot` */
  removeRobot(payload: { robotId?: string } = {}): Promise<unknown> {
    return this.a.act("remove_robot", payload);
  }
}

/** Where a named parameter's value comes from on a command line — see `SdkParam.cli` in the schema. */
export type CliSource = "positional" | "join" | "json" | "file" | "language" | "flag";
export interface CliParam {
  name: string;
  from?: CliSource;
  /** Coerce the value to a number. */
  number?: boolean;
}
export interface Command {
  /** Namespace name, or "" for a method on the client itself. */
  group: string;
  /** The typed-SDK method name — the CLI CALLS that method, so mapping lives in exactly one place. */
  verb: string;
  tool: string;
  /** A factory namespace's own params, bound before the verb (`commandagi social <platform> post …`). */
  factory?: { name: string; from: "positional" | "flag" }[];
  params?: CliParam[];
  /** The method takes a trailing options bag: remaining `--flags` (plus `--json`) fill it. */
  spread?: boolean;
  doc: string;
}

/** ONE ROW PER SCHEMA METHOD — generated, so the CLI cannot drift from the SDK. */
export const CLI_COMMANDS: readonly Command[] = [
  {
    group: "",
    verb: "constraints",
    tool: "agent_constraints",
    spread: true,
    doc: "Inspect or impose an immutable device-action state machine for this thread's agent.",
  },
  { group: "", verb: "whoami", tool: "whoami", doc: "The account this key belongs to." },
  {
    group: "",
    verb: "search",
    tool: "search_tools",
    params: [
      { name: "query", from: "join" },
      { name: "limit", from: "flag", number: true },
    ],
    doc: "Search the whole tool catalog by keyword.",
  },
  {
    group: "",
    verb: "run",
    tool: "run_code",
    params: [
      { name: "code", from: "file" },
      { name: "language", from: "language" },
      { name: "threadId", from: "flag" },
    ],
    doc: "Run a snippet server-side (JavaScript / TypeScript / Python).",
  },
  {
    group: "",
    verb: "post",
    tool: "post",
    spread: true,
    doc: "Publish a file to a connected social account.",
  },
  {
    group: "computer",
    verb: "screenshot",
    tool: "computer_screenshot",
    spread: true,
    doc: "Observe the computer's current screen.",
  },
  {
    group: "computer",
    verb: "act",
    tool: "computer_act",
    spread: true,
    doc: "One action/payload or an ordered actions array. Stops on first failure. Type a granted variable with text: '${env:NAME}'.",
  },
  { group: "threads", verb: "list", tool: "list_threads", doc: "Your threads." },
  {
    group: "threads",
    verb: "get",
    tool: "get_thread",
    params: [{ name: "threadId" }],
    doc: "One thread's detail.",
  },
  {
    group: "threads",
    verb: "create",
    tool: "create_thread",
    spread: true,
    doc: "Spawn a thread: {intent, snapshotId?, …}, or {agentless: true, snapshotId} for a world you drive.",
  },
  {
    group: "threads",
    verb: "send",
    tool: "send_message",
    params: [{ name: "threadId" }, { name: "text", from: "join" }],
    doc: "Message a thread.",
  },
  {
    group: "threads",
    verb: "events",
    tool: "thread_events",
    params: [{ name: "threadId" }],
    doc: "A thread's event log.",
  },
  {
    group: "threads",
    verb: "kill",
    tool: "kill_process",
    params: [{ name: "threadId" }],
    doc: "Stop a thread's run (the thread itself persists).",
  },
  { group: "embodiments", verb: "list", tool: "list_embodiments", doc: "Attached embodiments." },
  {
    group: "embodiments",
    verb: "launch",
    tool: "launch_embodiment",
    spread: true,
    doc: "Launch an embodiment into the thread: {kind?, snapshotId?, fromSnapshotId?}.",
  },
  {
    group: "embodiments",
    verb: "observe",
    tool: "observe",
    spread: true,
    doc: "The thread's observation plane: stream channels and the latest frame per embodiment.",
  },
  {
    group: "embodiments",
    verb: "controls",
    tool: "list_controls",
    params: [{ name: "embodimentId" }, { name: "threadId", from: "flag" }],
    doc: "What an embodiment can be driven with right now: channels, actions, payload schemas.",
  },
  {
    group: "embodiments",
    verb: "act",
    tool: "act",
    params: [
      { name: "embodimentId" },
      { name: "action" },
      { name: "payload", from: "json" },
      { name: "threadId", from: "flag" },
    ],
    doc: "Drive an embodiment with one declared action (see controls).",
  },
  {
    group: "embodiments",
    verb: "describe",
    tool: "describe_world",
    params: [{ name: "threadId", from: "flag" }],
    doc: "The live sim/robot world: robots, objects and poses the runtime reports.",
  },
  {
    group: "billing",
    verb: "prices",
    tool: "quote_passthrough",
    doc: "Every pass-through price, with its source and date.",
  },
  {
    group: "billing",
    verb: "quote",
    tool: "quote_passthrough",
    spread: true,
    doc: 'What a service costs before you buy it: {price: "twilio/us-sms", months?, units?, oneTime?}.',
  },
  {
    group: "billing",
    verb: "charges",
    tool: "list_passthrough_charges",
    params: [{ name: "limit", from: "flag", number: true }],
    doc: "The account's pass-through line items, monthly items and balance.",
  },
  {
    group: "memory",
    verb: "search",
    tool: "memory_search",
    params: [{ name: "query", from: "join" }],
    doc: "Recall by query (the drive's content index over memories/).",
  },
  {
    group: "memory",
    verb: "remember",
    tool: "memory_remember",
    spread: true,
    doc: "Write a memory file.",
  },
  {
    group: "memory",
    verb: "forget",
    tool: "memory_forget",
    params: [{ name: "path" }],
    doc: "Delete a memory file by its path.",
  },
  { group: "integrations", verb: "list", tool: "list_integrations", doc: "What's connected." },
  {
    group: "integrations",
    verb: "call",
    tool: "integration_call",
    params: [{ name: "integration" }],
    spread: true,
    doc: "Drive a provider's API (method/path/query/body).",
  },
  {
    group: "web",
    verb: "search",
    tool: "web_search",
    params: [{ name: "query", from: "join" }],
    spread: true,
    doc: "Search: kind search | news | academic | code | social | images | video; provider, limit, since, domains … in opts.",
  },
  {
    group: "web",
    verb: "fetch",
    tool: "web_fetch",
    params: [{ name: "url" }],
    spread: true,
    doc: "One page as clean text.",
  },
  {
    group: "web",
    verb: "crawl",
    tool: "web_crawl",
    params: [{ name: "url" }],
    spread: true,
    doc: "Many pages of one site (pages in opts).",
  },
  {
    group: "web",
    verb: "answer",
    tool: "web_answer",
    params: [{ name: "question", from: "join" }],
    spread: true,
    doc: "An answer with citations; depth research for a long report.",
  },
  {
    group: "web",
    verb: "providers",
    tool: "web_providers",
    doc: "The providers: what each offers and costs, and whether you can call it.",
  },
  {
    group: "postal",
    verb: "quote",
    tool: "postal_quote",
    params: [{ name: "source" }],
    spread: true,
    doc: "What mailing the letter or postcard would cost, and how it would go (its choices: the providers that can mail it). Costs nothing.",
  },
  {
    group: "postal",
    verb: "send",
    tool: "postal_send",
    params: [{ name: "source" }],
    spread: true,
    doc: "Mail the letter or postcard: charged first, recorded before it is sent, never retried. An agent needs a postal grant.",
  },
  {
    group: "postal",
    verb: "status",
    tool: "postal_status",
    params: [{ name: "piece", from: "flag" }],
    doc: "A sent piece's state and records; without a piece, the sent pieces.",
  },
  {
    group: "postal",
    verb: "cancel",
    tool: "postal_cancel",
    params: [{ name: "piece" }],
    doc: "Cancel a piece before it is printed; the charge comes back.",
  },
  {
    group: "postal",
    verb: "inbox",
    tool: "postal_inbox",
    params: [{ name: "mailbox", from: "flag" }],
    doc: "Your mailboxes, or one mailbox's received pieces with their scans.",
  },
  {
    group: "social",
    verb: "post",
    tool: "post",
    factory: [
      { name: "platform", from: "positional" },
      { name: "account", from: "flag" },
    ],
    params: [{ name: "fileId" }],
    spread: true,
    doc: "Publish a stored file to this account.",
  },
  {
    group: "social",
    verb: "call",
    tool: "integration_call",
    factory: [
      { name: "platform", from: "positional" },
      { name: "account", from: "flag" },
    ],
    params: [{ name: "method" }, { name: "path" }],
    spread: true,
    doc: "Raw API call as this account.",
  },
  {
    group: "phone",
    verb: "lines",
    tool: "list_phone_lines",
    params: [{ name: "ownerId", from: "flag" }],
    doc: "The lines you own or may use.",
  },
  {
    group: "phone",
    verb: "conversations",
    tool: "list_phone_conversations",
    params: [{ name: "lineId" }],
    doc: "A line's conversations, newest first.",
  },
  {
    group: "phone",
    verb: "read",
    tool: "read_phone_conversation",
    params: [{ name: "lineId" }, { name: "correspondent" }, { name: "after", from: "flag" }],
    doc: "One conversation's records (phone/<line>/<correspondent>.jsonl); `after` is a record id or an ISO time.",
  },
  {
    group: "phone",
    verb: "quote",
    tool: "quote_phone_number",
    params: [{ name: "e164" }, { name: "country" }, { name: "provider", from: "flag" }],
    doc: "What buying a number charges now, monthly and per use. Buys nothing.",
  },
  {
    group: "phone",
    verb: "text",
    tool: "send_text",
    params: [{ name: "lineId" }, { name: "to" }, { name: "body" }, { name: "media", from: "json" }],
    doc: "Send a text (an MMS with drive-file media). Recorded before it is sent; never retried.",
  },
  {
    group: "phone",
    verb: "call",
    tool: "place_call",
    params: [{ name: "lineId" }, { name: "to" }, { name: "bridgeTo", from: "flag" }],
    doc: "Click-to-call: ring the line's forward-to number (or a number your grant lists), then connect to `to`.",
  },
  {
    group: "vpn",
    verb: "status",
    tool: "vpn_status",
    doc: "The account's nodes, the exits it may use, the ACL and the exit grants.",
  },
  {
    group: "vpn",
    verb: "fetch",
    tool: "vpn_fetch",
    params: [{ name: "url" }],
    spread: true,
    doc: "Fetch a URL from a VPN exit's address (method, headers, body, exit in opts); refused without an exit grant.",
  },
];
